### ISSUE TITLE
请问在一个项目中如何让多个xm生效

### ISSUE THREAD

**Issue by xylinuxkernel** [AloneMonkey/MonkeyDev#102]
用Monk创建了一个Logos tweak，写的东西越来越多了，xm也更加杂乱无章了，尝试写多个xm发现并未被识别，请问这个改如何设置了。

**Comment by xylinuxkernel** [comment]
咋没人回复了，没人碰到过吗？

**Comment by AloneMonkey** [comment]
直接加，然后编译把生成的.mm加到编译源文件里面
