### ISSUE TITLE
发现个bug，'___FILEBASENAME___.h' file not found

### ISSUE THREAD

**Issue by deskOfDafa** [AloneMonkey/MonkeyDev#103]
如果工程名称超过两个汉字，那么“___Dylib.m”中就会出现error  "'___FILEBASENAME___.h' file not found"

@AloneMonkey  是不是你做了一两个汉字的处理啊,如果是汉字就替换成“_”,是这个样子吗???

**Comment by AloneMonkey** [comment]
不要使用中文。
