### ISSUE TITLE
找不到Cycript.framework

### ISSUE THREAD

**Issue by GL-ZHU** [AloneMonkey/MonkeyDev#107]
dyld: Library not loaded: /Library/Frameworks/Cycript.framework/Cycript
Referenced from: /var/containers/Bundle/Application/45405654-CAB4-449D-8BDD-CF19DFAA082D/MyWeWork.app/Frameworks/libMyWeWorkDylib.dylib
Reason: image not found

**Comment by AloneMonkey** [comment]
other link 里面去掉 -framework Cycript  改用  -l cycript
