### ISSUE TITLE
编译报错 ld: entry point (_main) undefined. for architecture arm64

### ISSUE THREAD

**Issue by iOSPrincekin** [AloneMonkey/MonkeyDev#108]
使用MonkeyApp开发的项目，编译时，出现如下错误：
ld: entry point (_main) undefined. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
使用的第三方库是   pod 'BaiduMapKit'

![image](https://user-images.githubusercontent.com/40560744/43675623-b6c582dc-9815-11e8-9eed-a082e732a7c5.png)
弄了好长时间还没解决大神给下思路

**Comment by AloneMonkey** [comment]
target 是动态库？

**Comment by BeanMan** [comment]
我也碰到了，我是新建立了一个ViewController然后在lib.m文件中引用，编译就报这个错，求大神指点

**Comment by AloneMonkey** [comment]
面向动态库编程

**Comment by iOSPrincekin** [comment]
大佬  可以具体些吗，我使用iPhone4s也是提示类似的  ld: entry point (_main) undefined. for architecture arm7，使用iPhone 6s 提示 ld: entry point (_main) undefined. for architecture arm64  谢谢啦

**Comment by xiaoer371** [comment]
@iOSPrincekin  @BeanMan     新建的文件 target 应该选择 xxx Dylib 。
