### ISSUE TITLE
应该是执行pack.sh 报错，但是ipa文件确实正确放置，而且前段时间都是好的

### ISSUE THREAD

**Issue by blackchena** [AloneMonkey/MonkeyDev#112]
packing...
Print: Entry, "CFBundleDisplayName", Does Not Exist
Print: Entry, "CFBundleURLTypes", Does Not Exist
[/Users/chensiyu/Desktop/JaiilBrokenDemo/JaiilBrokenDemo/TargetApp/demo.ipa]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/chensiyu/Desktop/JaiilBrokenDemo/JaiilBrokenDemo/TargetApp/demo.ipa or
        /Users/chensiyu/Desktop/JaiilBrokenDemo/JaiilBrokenDemo/TargetApp/demo.ipa.zip, and cannot find /Users/chensiyu/Desktop/JaiilBrokenDemo/JaiilBrokenDemo/TargetApp/demo.ipa.ZIP, period.
cp: /Users/chensiyu/Desktop/JaiilBrokenDemo/JaiilBrokenDemo/tmp/Payload/*.app: No such file or directory
Successfully inserted a LC_LOAD_DYLIB command
Found no restrict section to remove
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by AloneMonkey** [comment]
End-of-central-directory signature not found. Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive. 

ipa 包有问题。
