### ISSUE TITLE
git clone frida-iOS-dump报错: fatal: unable to access......

### ISSUE THREAD

**Issue by LuckyChen73p** [AloneMonkey/MonkeyDev#115]
庆哥, 我克隆frida-ios-dump的时候报错: fatal: unable to access 'https://github.com/AloneMonkey/frida-ios-dump.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443, 这个是什么问题啊

**Comment by AloneMonkey** [comment]
项目无关的问题，网上找答案
