### ISSUE TITLE
多线程运行cycript脚本会报BUG IN CLIENT OF sqlite3.dylib: illegal multi-threaded access to database connection

### ISSUE THREAD

**Issue by zivenni** [AloneMonkey/MonkeyDev#116]
脚本有一部分在子线程执行，一部分在主线程执行。然后会出现多线程访问sqlite3数据库错误。
![image](https://user-images.githubusercontent.com/8642108/45212114-a49fb980-b2c6-11e8-9853-9aee0f05c4e3.png)
控制台输出的错误信息：
[logging] BUG IN CLIENT OF sqlite3.dylib: illegal multi-threaded access to database connection

![image](https://user-images.githubusercontent.com/8642108/45212189-d6188500-b2c6-11e8-8ac7-ecb0cda09800.png)

![image](https://user-images.githubusercontent.com/8642108/45212197-ddd82980-b2c6-11e8-8e2f-3cc418fa5f07.png)

**Comment by AloneMonkey** [comment]
自己加锁吧

**Comment by zivenni** [comment]
我没有访问数据库，是脚本运行的时候libcycript.dylib会访问libcycript.db，问一下，这个要怎么加锁？

**Comment by AloneMonkey** [comment]
你是说正常项目run的时候就出现这个情况吗？

**Comment by zivenni** [comment]
是的，项目启动的时候自动加载了一个cycript脚本，脚本里有些操作放在子线程，然后就会出现问题。如果都在主线程的话，就是正常运行的。

**Comment by AloneMonkey** [comment]
你是自己写的cycript脚本，里面操作了UI吗？还是说就是MD自带的脚本？

**Comment by zivenni** [comment]
https://github.com/zivenni/testcycript.git

写了个demo.cy，在控制台多运行几次后就会报错了

`(function(demo){
 
 	testThread = function() {
 		for(var i=0;i<1000;i++){
			[Common runBlockInThread:^void(){
			 	NSLog("Thread");
				[Common runBlockInMain:^void(){
				 	NSLog("Main");
				}];
			 }];
 		}
 	}
 
})(demo);`

**Comment by zivenni** [comment]
原来是我写的多线程有问题，忽略吧。。。
