### ISSUE TITLE
请问MonkeyDev怎么给添加自己的dylib?

### ISSUE THREAD

**Issue by ZHDeveloper** [AloneMonkey/MonkeyDev#117]
我导出越狱的插件dylib，怎么添加mokeydev的dylib中？

**Comment by ZHDeveloper** [comment]
<img width="785" alt="2018-09-10 3 35 15" src="https://user-images.githubusercontent.com/12929278/45282986-326de580-b50f-11e8-8ac2-ab0b02e1a0fc.png">
<img width="1140" alt="2018-09-10 3 34 59" src="https://user-images.githubusercontent.com/12929278/45282992-36016c80-b50f-11e8-93df-e51d1868a610.png">

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%9D%9E%E8%B6%8A%E7%8B%B1App%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90frida

麻烦先读一遍wiki
