### ISSUE TITLE
dyld`__abort_with_payload

### ISSUE THREAD

**Issue by ZhiJianShuSheng** [AloneMonkey/MonkeyDev#12]
Hi,I according to this wiki,but got this error. My system version is 10.10.3 and not break.
dyld: Library not loaded: /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate

**Comment by AloneMonkey** [comment]
is MonkeyApp？ 

Can you describe the steps you are doing?

Are you add CydiaSubstrate by youself?

**Comment by ZuhanLin** [comment]
没法添加自己的reveal.framework，替换了revealServer.framework  就会打包失败

**Comment by AloneMonkey** [comment]
@ZuhanLin https://github.com/AloneMonkey/MonkeyDev/wiki/Q&A#eight
