### ISSUE TITLE
代理环境下面安装脚本失败

### ISSUE THREAD

**Issue by liqiushui** [AloneMonkey/MonkeyDev#120]
curl: (56) Received HTTP code 504 from proxy after CONNECT
Failed to download https://raw.githubusercontent.com/AloneMonkey/frida-ios-dump/3.x/dump.py to /opt/MonkeyDev/bin/dump.py

需要指定代理
``

#下载文件
function downloadFile() # args: sourceUrl, targetPath
{
	local sourceUrl="$1"
	local targetPath="$2"
	local curlPath

	mkdir -p "${targetPath%/*}" || \
		panic $? "Failed to make directory: ${targetPath%/*}"

	curlPath=`which curl` || \
		panic $? "Failed to get curl path"

	curl -x  http:proxy:proxyport--output "$targetPath" "$sourceUrl" || \
		panic $? "Failed to download $sourceUrl to $targetPath"
}

**Comment by carppond** [comment]
这个是需要配置什么东西吗？

**Comment by carppond** [comment]
http:proxy:proxyport 怎么配置
