### ISSUE TITLE
The file “sanguo” couldn’t be opened because you don’t have permission to view it.

### ISSUE THREAD

**Issue by yinjimmy** [AloneMonkey/MonkeyDev#121]
Xcode 9.4
![image](https://user-images.githubusercontent.com/5056328/45662284-cd7c4600-bb33-11e8-9f69-6205bcd3a508.png)

如果不加 ipa，可以正常运行。

**Comment by AloneMonkey** [comment]
测试没出现这个情况，你可以clean试试

**Comment by yinjimmy** [comment]
![image](https://user-images.githubusercontent.com/5056328/45696175-93439080-bb95-11e8-9f14-259fec8ece03.png)

Xcode 10, iOS 12 出现崩溃。

**Comment by yinjimmy** [comment]
"permission" 的问题有可能是 应用名称是 中文 的问题，不过也检查不到了。开发环境都升级了。

**Comment by blloc** [comment]
是的 真机跑不起来了

**Comment by AloneMonkey** [comment]
@blloc 你是xcode几，报什么错？

**Comment by blloc** [comment]
xcode 10 
![image](https://user-images.githubusercontent.com/8268339/45728203-9cfedf80-bbf9-11e8-80d5-6131e3c1c3f0.png)

**Comment by blloc** [comment]
跑之前的项目报，XCode App installation failed (A valid provisioning profile for this executable was not found)。删除本地保存的 mobileprovision 文件也是不行，上面那个是我新建的工程报的错

**Comment by MrQQQQQQQQQQ** [comment]
今天Xcode 升级 到10 之后，就报  couldn’t be opened because you don’t have permission to view it 。之前 Xcode 9.x的时候 都是正常的

**Comment by blloc** [comment]
In Xcode, go to File->Project/Workspace settings.
Change the build system to Legacy Build system.

应该还不支持新的吧，我切换回来就正常了。
https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce

@AloneMonkey

**Comment by yinjimmy** [comment]
重新安装了 MonkeyDev，Xcode 10 + iPhone 4s 9.3.5 (破解) + `New Build System` ，可以正确加载，运行 IPA 了，谢谢。
