### ISSUE TITLE
请教安装失败的问题

### ISSUE THREAD

**Issue by whqfor** [AloneMonkey/MonkeyDev#122]
bogon:~ XX$ sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-install)"
Downloading MonkeyDev base from Github...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9116  100  9116    0     0  23500      0 --:--:-- --:--:-- --:--:-- 23555
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
Failed to extract /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sh.WZloIqyK/file.tar.gz to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/sh.gSbhB8ht

Mac OS 10.13.6 (17G65)  Xcode 9.4.1 ，我和同事两台电脑按照wiki都不能安装

**Comment by whqfor** [comment]
![2018-09-19 17 34 50](https://user-images.githubusercontent.com/12791878/45744953-59749780-bc32-11e8-9b1d-74c8a3bb2ec1.png)   可能是这个文件没有读写权限？ 网络应该是正常的，挂不挂VPN都不行，下班后用家里的网络试试

**Comment by whqfor** [comment]
家里网络可以

**Comment by crifan** [comment]
我也遇到同样问题：
```bash
Failed to extract /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/md-install.gvGnDuMp/file.tar.gz to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/md-install.KQllUKhp
```

* 原因：和网络没关系。和临时文件权限有关系
此处的临时文件所属目录 `/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T`的权限是`drwx------@`

-》意思是，除了owner自己，other和group都没有权限（包括基本的read操作），导致后续报错。

* 规避办法：

手动创建一个临时目录：`mkdir -p /tmp/md_install/tempdirs`

把脚本`bin/md-install`改为：

```bash
# export tempDirsFile="`mktemp -d -t $scriptName`/tempdirs"
export tempDirsFile="/tmp/md_install/tempdirs"
```
即可。
