### ISSUE TITLE
可以还原到以前版本吗

### ISSUE THREAD

**Issue by AsTryE** [AloneMonkey/MonkeyDev#126]
1. 最近升级了MonkeyDev和Xcode10，发现一个swift和oc混淆的APP，想研究下混编项目是否支持，swift怎么混淆。
2. 安装上去，登录之后报错，之前用老版本是好的。经过测试，我发现在Products生成的APP目录，将Info.plist修改为原来的APP的Info.plist，就是说不用生成的Info.plist，手动修改里面的bundle ID，然后，执行`createIPA.command` 命令，安装APP登录账号，没任何问题，所以应该是Info.plist问题导致的。
3. 不改Info.plsit，APP进首页可以，但是登录闪退。之前老版的MonkeyDev可以，安装和登录都不闪退。

**Comment by AloneMonkey** [comment]
对比下Info.plist文件有什么不同？

**Comment by AsTryE** [comment]
里面字段有点多，不好对比，原始文件大小20K，新生成的17K。

**Comment by AsTryE** [comment]
有的APP是正常的，不是全部

**Comment by AloneMonkey** [comment]
什么App不正常？

**Comment by AsTryE** [comment]
一个叫`吹牛`的APP，App Store里面可以下载。

**Comment by AsTryE** [comment]
想搞个抢红包的功能，`swift`有点难分析。

**Comment by AsTryE** [comment]
一个个对比了，终于发现哪个字段问题了 `Bundle name` 字段有问题，需设置为 `Executable file` 字段一样的值，但是这里的值是 `吹牛`

**Comment by AloneMonkey** [comment]
好的，我晚上看下~

**Comment by AsTryE** [comment]
我改了下`pack.sh`，基本可以不闪退了：
1. 128行，新增：`TARGET_EXECUTABLE_NAME=$(/usr/libexec/PlistBuddy -c "Print CFBundleExecutable" "${TARGET_INFO_PLIST}" 2>/dev/null)`
2. 172行：更新Info.plist部分更改为取可执行文件名。
修改如下：
```
# Update Info.plist for Target App
	if [[ "${TARGET_DISPLAY_NAME}" != "" ]]; then
		/usr/libexec/PlistBuddy -c "Set :CFBundleName ${TARGET_EXECUTABLE_NAME}" "${TARGET_INFO_PLIST}"
		for file in `ls "${BUILD_APP_PATH}"`;
		do
			extension="${file#*.}"
		    if [[ -d "${BUILD_APP_PATH}/$file" ]]; then
				if [[ "${extension}" == "lproj" ]]; then
					if [[ -f "${BUILD_APP_PATH}/${file}/InfoPlist.strings" ]];then
						/usr/libexec/PlistBuddy -c "Set :CFBundleDisplayName ${TARGET_DISPLAY_NAME}" "${BUILD_APP_PATH}/${file}/InfoPlist.strings"
						/usr/libexec/PlistBuddy -c "Set :CFBundleName ${TARGET_EXECUTABLE_NAME}" "${BUILD_APP_PATH}/${file}/InfoPlist.strings"

					fi
		    	fi
			fi
		done
	fi
```
目前这样取到的值是正确的，可以试试看。

**Comment by AloneMonkey** [comment]
ok, thanks

**Comment by AsTryE** [comment]
嗯，这样也可以。不修改他，就用原来的。只不过这里为什么要修改呢。

**Comment by AloneMonkey** [comment]
具体不太记得了，暂时把这两行删了，你更新下试试，之前的其它app有没有问题。

**Comment by AsTryE** [comment]
试了下没问题。--------看了几个APP的原始的`Info.plist`信息，发现`CFBundleName`的值都是和`CFBundleExecutable`一样，而不是`CFBundleDisplayName`。奇怪的是，我试过微信，`CFBundleName`的值错了，不是`WeChat`，而是`微信`,这个运行却没问题。

**Comment by AsTryE** [comment]
正确的，显示名称是根据`CFBundleDisplayName `这个值来的啊
