### ISSUE TITLE
dyld: Library not loaded: /Library/Frameworks/Cycript.framework/Cycript

### ISSUE THREAD

**Issue by kobe1941** [AloneMonkey/MonkeyDev#128]
如题，升级了Xcode，换了新版的ipa包后报错，已确认ruby版本没问题，终端执行cycript 也OK。但是工程在运行的时候还是会报这个错？help..

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev/issues/107

**Comment by kobe1941** [comment]
![image](https://user-images.githubusercontent.com/7099017/47089701-f9ced380-d253-11e8-88b5-5e58a2627bde.png)
