### ISSUE TITLE
重写任何方法时候，调用self都错误 ？

### ISSUE THREAD

**Issue by swlfigo** [AloneMonkey/MonkeyDev#13]
重写xxx的时候，改写其方法，例如
CHOptimizedMethod1(self, void, xxx, viewDidAppear, BOOL, arg1){
}
中调用self，就提示
Receiver type 'xxx' for instance message is a forward declaration?
请问是哪里问题，谢谢

**Comment by AloneMonkey** [comment]
看下这里面的例子？

https://github.com/AloneMonkey/MonkeyDevSpecs

**Comment by AloneMonkey** [comment]
没写CHDeclareClass(xxxx)  ??

**Comment by iOSleep** [comment]
@swlfigo 这里是arc，网上类似的demo都是mrc的，所以，请使用runtime的方式创建。
@AloneMonkey 庆哥，要不把这个写一下放到wiki里吧，感觉看到好几次这个问题了😅

**Comment by AloneMonkey** [comment]
@iOSleep 恩，让他们多看看pod里面的例子。

**Comment by swlfigo** [comment]
@AloneMonkey @iOSleep  好的~谢谢我看看例子啊~刚刚学习搞了几个App，还有个问题就是在PP上下了个爱奇艺的app，新建一个项目运行之后，网络接口基本都访问不了~是不是姿势不对~请指点一下

**Comment by swlfigo** [comment]
@AloneMonkey  @iOSleep  好的谢谢我看看例子
刚刚学习搞了几个App，还有个问题就是在PP上下了个爱奇艺的app，新建一个项目运行之后，网络接口基本都访问不了,是不是姿势不对呢？请大大指点一下

**Comment by AloneMonkey** [comment]
@swlfigo  我这里没问题，你开了代理吧

**Comment by swlfigo** [comment]
@AloneMonkey 呃没有呢，之前还试了下QQ音乐，PP上下的,QQ登陆是一直提示错误.微信登陆就没问题

**Comment by AloneMonkey** [comment]
@swlfigo 我这没问题，你再看看吧~

**Comment by swlfigo** [comment]
@AloneMonkey 好的谢谢大大~

**Comment by iOSleep** [comment]
@isbase  参考 [https://github.com/AloneMonkey/MonkeyDevSpecs](https://github.com/AloneMonkey/MonkeyDevSpecs) 中的各个项目
runtime方式
``` objective-c
[[objc_getClass("SomeClassName") alloc] init]
```

**Comment by AloneMonkey** [comment]
@isbase  

```
@interface SomeClassName : NSObject
@property (copy, nonatomic) NSString *somePropertyName;
@end
```

**Comment by isbase** [comment]
@AloneMonkey  嗯.我其实还是用这种方式解决的.. 之前粗心,少写了:UIViewController给我郁闷好久...
@interface FindFriendEntryViewController:UIViewController
@end

@iOSleep 谢谢回复了.我就是想获取 SElF之前粗心少写东西了..... 很尴尬....
