### ISSUE TITLE
MacApp Shell packing 报错

### ISSUE THREAD

**Issue by HolmesZhao** [AloneMonkey/MonkeyDev#138]
最新版的 `MD`, `macOS High Sierra`, `Xcode 9.4.1`
```
packing...
2018-12-07 21:48:27.249 Near Lock[3454:558478] [AntiAntiDebug Init]
SubHookMessageEx: substitute_hook_objc_message returned SUBSTITUTE_ERR_NO_SUCH_SELECTOR
/opt/MonkeyDev/Tools/mpack.sh: line 57:  3454 Abort trap: 6           "$APP_BINARY_PATH"
Command /bin/sh failed with exit code 134
```

**Comment by youngerbyte** [comment]
> 最新版的 `MD`, `macOS High Sierra`, `Xcode 9.4.1`
> 
> ```
> packing...
> 2018-12-07 21:48:27.249 Near Lock[3454:558478] [AntiAntiDebug Init]
> SubHookMessageEx: substitute_hook_objc_message returned SUBSTITUTE_ERR_NO_SUCH_SELECTOR
> /opt/MonkeyDev/Tools/mpack.sh: line 57:  3454 Abort trap: 6           "$APP_BINARY_PATH"
> Command /bin/sh failed with exit code 134
> ```

哥们怎么解决的

**Comment by HolmesZhao** [comment]
> > 最新版的 `MD`, `macOS High Sierra`, `Xcode 9.4.1`
> > ```
> > packing...
> > 2018-12-07 21:48:27.249 Near Lock[3454:558478] [AntiAntiDebug Init]
> > SubHookMessageEx: substitute_hook_objc_message returned SUBSTITUTE_ERR_NO_SUCH_SELECTOR
> > /opt/MonkeyDev/Tools/mpack.sh: line 57:  3454 Abort trap: 6           "$APP_BINARY_PATH"
> > Command /bin/sh failed with exit code 134
> > ```
> 
> 哥们怎么解决的

太久了...我忘记了

**Comment by caihongxiaoyang** [comment]
同问，如何解决的？

**Comment by HolmesZhao** [comment]
> 同问，如何解决的？

最近也遇到了, 这个只要你保证 `/Applications/xx.app` 和 targetapp 目录下的 `xx.app` 保持同一个干净的包就行

**Comment by zhoudianyou** [comment]
解决方案：
在Xcode 项目内: Targets ---> Build Phases ---> Run Script 
勾选：Show environment variables in build log
勾选:   Run script only when installing 
就能解决 如上编译错误

**Comment by 342261733** [comment]
Env: macOS Monterey 12.6, Xcode Version 14.0.1 (14A400)
Error:
2023-01-09 11:13:49.836 [44957:10866345] [AntiAntiDebug Init]
/opt/MonkeyDev/Tools/mpack.sh: line 61: 44957 Bus error: 10           "$APP_BINARY_PATH"

**Comment by 342261733** [comment]
Env: macOS Monterey 12.6, Xcode Version 14.0.1 (14A400)
Error:
2023-01-09 11:13:49.836 [44957:10866345] [AntiAntiDebug Init]
/opt/MonkeyDev/Tools/mpack.sh: line 61: 44957 Bus error: 10           "$APP_BINARY_PATH"

尝试上面的解决方法，均不好用。还有别的解决方法么？

**Comment by 342261733** [comment]
> Env: macOS Monterey 12.6, Xcode Version 14.0.1 (14A400) Error: 2023-01-09 11:13:49.836 [44957:10866345] [AntiAntiDebug Init] /opt/MonkeyDev/Tools/mpack.sh: line 61: 44957 Bus error: 10 "$APP_BINARY_PATH"
> 
> 尝试上面的解决方法，均不好用。还有别的解决方法么？

最后解决了，原来是 fishhook 的版本太老了，更新下工程里的 fishhook 为最新版就解决了
