### ISSUE TITLE
打开AntiAntiDebug注释不生效

### ISSUE THREAD

**Issue by CheaterHu** [AloneMonkey/MonkeyDev#139]
逆向支付宝，按照正常流程创建monkeyAPP，运行之后直接闪退，报 LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted。按照https://github.com/AloneMonkey/MonkeyDev/issues/44  这个方式打开注释，运行会一直卡在启动屏，而且xcode也会卡死，怀疑是进入了死循环。
自己琢磨之后，还是AntiAntiDebug中代码注释（rebind_symbols((struct rebinding[1]){{"sysctl", my_sysctl, (void*)&orig_sysctl}},1);），然后将BuildSetting 中的MONKEYDEV_DEFAULT_BUNDLEID设置为YES 能正常运行，但是最后还是崩溃，日志输出：Attempt to use unknown class 0x1092ad580.
![2018-12-11 14 34 28](https://user-images.githubusercontent.com/12546922/49782864-d48dab80-fd52-11e8-8ee5-b09fb7a34571.png)
![2018-12-11 14 33 59](https://user-images.githubusercontent.com/12546922/49782866-d7889c00-fd52-11e8-88b8-fcd8398211b4.png)

**Comment by CheaterHu** [comment]
设备是iOS12.1.1 iPhone XR

**Comment by CheaterHu** [comment]
arm64e架构 好像不行，反调试会死锁。

**Comment by CheaterHu** [comment]
@AloneMonkey 大佬能不能解答一下为什么

**Comment by lihongwwei** [comment]
@AloneMonkey 同求大佬解答
