### ISSUE TITLE
Wiki 里的图片全挂了

### ISSUE THREAD

**Issue by kukushi** [AloneMonkey/MonkeyDev#143]
希望修复一下

**Comment by AloneMonkey** [comment]
代理关一下。

**Comment by Naville** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/5205699/50569684-6b9ebf80-0d63-11e9-8301-f089eef962f2.png">

**Comment by kukushi** [comment]
@AloneMonkey 
关掉代理也看不到。。

**Comment by AloneMonkey** [comment]
@kukushi 现在应该好了。

**Comment by abiuDoIT** [comment]
> @kukushi 现在应该好了。

还是挂的啊,看图全靠自己臆想了现在😂
