### ISSUE TITLE
MonkeyDev 如何用生产证书完成签名打包？

### ISSUE THREAD

**Issue by DyoungYu** [AloneMonkey/MonkeyDev#145]
当我用MonkeyDev调试并修改别人的应用之后，想用企业证书的生产证书完成打包，请问应当如何操作呢？
大神提供的createIPA.command指令打包也是针对开发环境编译生成的APP文件进行打包。

**Comment by Peterae** [comment]
请问你这个问题解决了吗?我也想知道生产证书怎么打包？谢谢！
