### ISSUE TITLE
App installation failed

### ISSUE THREAD

**Issue by Peterae** [AloneMonkey/MonkeyDev#148]
请问工程集成的 Reveal 版本是多少？我换最新版本 20 和老版本都提示版本不对，替换 /opt/MonkeyDev/frameworks 后运行安装报错！
This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique

**Comment by AloneMonkey** [comment]
删了原来的，换成新的

**Comment by Peterae** [comment]
> 删了原来的，换成新的

一开始我也以为是 id 重复，后来发现删了没用，改 id 也没用。最后没替换一个版本一个版本的试了 14 可以

**Comment by 252320993** [comment]
亲测删除旧的之后clean一下，再编译可以解决。

**Comment by Peterae** [comment]
下次升级试试，我是一直试，一直找了个匹配的版本。。。

**Comment by Aix6** [comment]
> 亲测删除旧的之后clean一下，再编译可以解决。

下次升级试试，我是一直试，一直找了个匹配的版本。。。谢谢

**Comment by B0rn2d** [comment]
> > 删了原来的，换成新的
> 
> 一开始我也以为是 id 重复，后来发现删了没用，改 id 也没用。最后没替换一个版本一个版本的试了 14 可以

解决了，感谢！使用了14就可以了，而且RevealFramework都不需要替换
