### ISSUE TITLE
没找到MethodTraceConfig.plist这个文件

### ISSUE THREAD

**Issue by wonderffee** [AloneMonkey/MonkeyDev#16]
链接
 https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%9D%9E%E8%B6%8A%E7%8B%B1App%E9%9B%86%E6%88%90 里说有，搜索这个repository也没有找到关键字啊

**Comment by AloneMonkey** [comment]
先md-update 更新下，然后新建一个项目就有了。

**Comment by wonderffee** [comment]
是我疏忽了，3q
