### ISSUE TITLE
tvOS support?

### ISSUE THREAD

**Issue by qiudaomao** [AloneMonkey/MonkeyDev#164]
Thanks for this amazing tool, it's working wonderful in jail and un-jailbroken iOS device.

Hope this project support tvOS as well

+ tvOS is a modified version of iOS, it can share most code with iOS
+ tweaks based on theos are working well in tvOS
+ cyscript is working
+ there also has a package manager named NitoTV which functional like cydia
+ bfdecrypt is working on tvOS11, we can get decrypted ipa for tvOS.

Any tips to make an MonkeyApp project for tvOS?

Referer: [uicache - a tvos theos project](https://nito.tv:3000/NitoTV/uicache/src/master)

**Comment by qiudaomao** [comment]
I manually change the target type to tvOS and do some modification to the dylib build options, it is working for tvOS now. close it, Although a good template will helpping.

**Comment by CokePokes** [comment]
@qiudaomao Can you share the file?

Edit: Actually I figured it out, change `iphoneos` to `appletvos` in the md file as well as doing what qiudaomao says above. Also, change `iphoneos-arm` in the control file to `appletvos-arm64`
