### ISSUE TITLE
我运行报个错 不知道怎么解决了 求解

### ISSUE THREAD

**Issue by ws1227** [AloneMonkey/MonkeyDev#17]
dyld: Library not loaded: @executable_path/Frameworks/libRHWeChatDylib.dylib
  Referenced from: /var/containers/Bundle/Application/E2171276-D069-4D9B-8A43-7ABBF71B7567/RHWeChat.app/Calculator
  Reason: image not found

**Comment by AloneMonkey** [comment]
看过Wiki了吗？

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev/wiki/Q&A#two

**Comment by ws1227** [comment]
看了 就是你说的这句话吗  ‘编译提示找不到到libxxxDylib.dylib’

**Comment by ws1227** [comment]
现在是报 
Undefined symbols for architecture armv7:
  "_CYListenServer", referenced from:
      ___entry_block_invoke in RHWeChatDylib-55D48DB43DA9169C.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AloneMonkey** [comment]
你是自己砸壳的还是PP助手下载的越狱应用？  
动态库的Build Settings下Build Active Architecture Only Debug改成No试试

**Comment by ws1227** [comment]
我pp助手下载的

**Comment by AloneMonkey** [comment]
除了拖入ipa和添加依赖不需要其它操作了，你还有做其它的操作吗？

**Comment by ws1227** [comment]
[可能和我本地环境有关吧](http://art13.photozou.jp/pub/534/3167534/photo/250905907_org.v1505445023.png)

[报错图](http://art13.photozou.jp/pub/534/3167534/photo/250905908_org.v1505445029.png)
![](http://art13.photozou.jp/pub/534/3167534/photo/250905907_org.v1505445023.png)

**Comment by AloneMonkey** [comment]
又是模拟器？要起飞啊

**Comment by ws1227** [comment]
手机

**Comment by ws1227** [comment]
[如果方便你可以看看我的一个demo](https://github.com/ws1227/MonkeyDevtest)

**Comment by AloneMonkey** [comment]
你为什么要改我模块的配置？？？？？？

**Comment by ws1227** [comment]
哪个？我没改啥配置吧

**Comment by ws1227** [comment]
我再从新弄个项目看看啊

**Comment by ws1227** [comment]
新建项目居然好了 我不知道改啥了 抱歉这么麻烦你了

**Comment by wonderffee** [comment]
"_CYListenServer", referenced from 这个错误应该是删除了Cycript.framework

**Comment by Bone111** [comment]
dyld: Library not loaded: @executable_path/Frameworks/libDemoHaiDylib.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/AB5CDA42-5C27-4A54-A4B2-F66CAE02137C/DemoHai.app/ytmallApp
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/AB5CDA42-5C27-4A54-A4B2-F66CAE02137C/DemoHai.app/Frameworks/libDemoHaiDylib.dylib: mach-o, but wrong architecture
	/private/var/mobile/Containers/Bundle/Application/AB5CDA42-5C27-4A54-A4B2-F66CAE02137C/DemoHai.app/Frameworks/libDemoHaiDylib.dylib: mach-o, but wrong architecture

- Hook 1 (expr -- @import UIKit)

- Hook 2 (target stop-hook disable)
(lldb)

**Comment by GitHub-hyj** [comment]
大神你好，我遇到一个问题，请教一下如何解决
dyld: Library not loaded: /Library/Frameworks/Cycript.framework/Cycript
  Referenced from: /var/containers/Bundle/Application/6A18E534-113D-4115-8CFD-F0D9AE954926/WeChat.app/Frameworks/libWeChatDylib.dylib
  Reason: image not found
