### ISSUE TITLE
mac插件编译卡住

### ISSUE THREAD

**Issue by fate233** [AloneMonkey/MonkeyDev#175]
大佬您好。

新建Mac插件后，无改动，cmd+b启动，QQ自动打开了，编译在进行中（没有报错），等了半小时没进展，卡住了。

building 2 of 5 tasks

求指点！

**Comment by fate233** [comment]
![image](https://user-images.githubusercontent.com/7871447/55782105-329e8580-5ade-11e9-8aed-dcbe4cd93059.png)

**Comment by fate233** [comment]
我的错！！！ 不用等他，直接attach就好了！

**Comment by fate233** [comment]
关了，谢谢！

**Comment by cuiyu8580** [comment]
能直接进行lldb调试吗？可不可以留个联系方式交流一下？
