### ISSUE TITLE
Method Trace is disabled

### ISSUE THREAD

**Issue by xhzth7091** [AloneMonkey/MonkeyDev#187]
🎉!!！congratulations!!！🎉
👍----------------insert dylib success----------------👍
[MethodTrace] 
📚--------------------OCMethodTrace(Usage)-------------------📚
https://github.com/omxcodec/OCMethodTrace/blob/master/README.md
📚--------------------OCMethodTrace(Usage)-------------------📚
[MethodTrace] logLevel: 0: logWhen: 0 traceFlag: 2 traceObject: 0(未指定类)
[MethodTrace] Method Trace is disabled

这需要怎么设置啊，我运行真机奔溃，Method Trace is disabled，是armv7的架构
![Xnip2019-05-20_11-11-30](https://user-images.githubusercontent.com/13980546/57994508-20a5fe80-7af0-11e9-8d73-722869710e33.jpg)
![Xnip2019-05-20_11-11-55](https://user-images.githubusercontent.com/13980546/57994518-256ab280-7af0-11e9-8d39-773b36b62aa4.jpg)

**Comment by dakezuo** [comment]
@xhzth7091 怎么解决的？

**Comment by PilotLee** [comment]
解决了都不说一声吗 我擦
