### ISSUE TITLE
有办法打印某个方法里面的所有方法跟踪日志吗？

### ISSUE THREAD

**Issue by wonderffee** [AloneMonkey/MonkeyDev#19]
我知道里面的方法跟踪日志功能借鉴了ANYMethodLog，但是要不就是跟踪一个类中的所有方法，要不就是跟踪指定方法，没有第三选择，如果想指定特定类特定方法，打印这个特定方法里面的所有方法调用，有可能实现吗？可能指望不上 ANYMethodLog，借助HooZz有可能实现这功能吗？

**Comment by AloneMonkey** [comment]
暂时觉得这个需求不是很强烈，而且需要考虑到比较多的因素，先自己通过静态分析加调试把。
