### ISSUE TITLE
在Dylib.mCHOptimizedMethod2包含一个block类型，报错，我不想写成id，因为我要打印block的参数

### ISSUE THREAD

**Issue by xhzth7091** [AloneMonkey/MonkeyDev#196]
在Dylib.mCHOptimizedMethod2包含一个block类型，报错，我不想写成id，因为我要打印block里dic的参数，你书上没有写在Dylib.m里，有block的参数，应该怎么写，求教 
![Xnip2019-06-03_17-50-46](https://user-images.githubusercontent.com/13980546/58793190-3bb45a80-8628-11e9-81dd-161ab9c1d4c8.jpg)

**Comment by qweqwqsqwwew** [comment]
https://github.com/qweqwqsqwwew/ReTools/tree/master
