### ISSUE TITLE
最后编译出现问题

### ISSUE THREAD

**Issue by BestKai** [AloneMonkey/MonkeyDev#2]
![144fd6e8-ec1c-438e-bc52-b4916c3bd6c9](https://user-images.githubusercontent.com/8436462/28445158-265a5cea-6df5-11e7-9066-56af7190f646.png)

**Comment by AloneMonkey** [comment]
本地存在多个证书，只有一个开发者证书就行

**Comment by BestKai** [comment]
只能把多余的证书删掉吗？

**Comment by AloneMonkey** [comment]
或者关闭自动签名，然后在build setting里面的签名设置指定使用的证书，使用同一个。

**Comment by BestKai** [comment]
还是会有一样的问题。。
![b8ee3919-016c-4dc6-9c45-7c7977807b39](https://user-images.githubusercontent.com/8436462/28460764-052c2d5e-6e46-11e7-9e46-6ea5d23e311f.png)
![f1fb2923-9bd9-46dd-946c-4a7eddc82d9a](https://user-images.githubusercontent.com/8436462/28460765-052d73ee-6e46-11e7-9022-d4d1758eaca1.png)

**Comment by AloneMonkey** [comment]
你加下README.md的微信群。

**Comment by AloneMonkey** [comment]
Build Settings里面的Signing也配置了吗？

**Comment by AloneMonkey** [comment]
此类问题解决办法:

1.  本地只保留一个证书
2. 关闭自动签名，两个Target手动选择证书，并在Build Settings里面的Signing也配置证书即可解决。

**Comment by loufq** [comment]
只能删，手动选只能选择开发者，不能具体到某个证书，所以只能删
