### ISSUE TITLE
请问一下能否通过MonkeyDev注入后，获得新的包，.app的或者是ipa

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#20]

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%9D%9E%E8%B6%8A%E7%8B%B1App%E9%9B%86%E6%88%90#%E7%94%9F%E6%88%90ipa


多看Wiki

**Comment by zhoupenghao** [comment]
很全面，原来在最底下呀，谢谢啦，#18  close吧，表情包子还是好玩的
