### ISSUE TITLE
关于添加图片资源的问题

### ISSUE THREAD

**Issue by cocoawork** [AloneMonkey/MonkeyDev#212]
你好!
我是新接触逆向相关, 在使用MonkeyDev逆向App时, 新添加的图片资源无法被加载, 查找原因说是路径问题, 不知道图片资源应该放在哪里? 还望指点!谢谢
附上工程目录如下
![图片](https://user-images.githubusercontent.com/18298091/63763816-128a2a00-c8f8-11e9-9ba0-95ef51c37a6e.png)

**Comment by lijuanjuan0117** [comment]
请问这个问题解决了吗？怎么添加图片资源啊？
