### ISSUE TITLE
Xcode11.0(11A419c)

### ISSUE THREAD

**Issue by jinean** [AloneMonkey/MonkeyDev#214]
Command-line Tool
unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos' 

=>>
sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-update)"

**Comment by Yongle-Fu** [comment]
building for iOS, but linking in .tbd file (/opt/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd) 
built for iOS Simulator, file '/opt/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd' for architecture arm64

**Comment by liaogang** [comment]
找到 /opt/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd  删掉arm64之外的所有指令集

**Comment by wxq491216** [comment]
怎么删除，能更具体一点么？lipo命令不能作用于tbd文件

**Comment by s84088722** [comment]
> Command-line Tool
> unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos'

@AloneMonkey 我也是升级到xcode11就提示这个 命令行无法编译 请问怎么解决呢

**Comment by Yongle-Fu** [comment]
sublime  text

**Comment by 850664600** [comment]
安装完monkeydevy无法在xcode显示

**Comment by 850664600** [comment]
安装完monkeydevy无法在xcode显示

**Comment by 850664600** [comment]
安装完monkeydev无法在xcode显示

**Comment by sportsminer** [comment]
> Command-line Tool
> unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos'

xcode11.2也碰到了这个问题，怎么解决？

**Comment by lubbo** [comment]
Does it works with Xcode 11.3?

**Comment by jinean** [comment]
sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-update)"

**Comment by Mars1989sh** [comment]
安装完monkeydev无法在xcode显示 求大神指点
