### ISSUE TITLE
求助 xcode11 CaptainHook Tweak   编译出现错误 An empty identity is not valid when signing a binary for the product type 'Dynamic Library'

### ISSUE THREAD

**Issue by iphone5s** [AloneMonkey/MonkeyDev#218]
An empty identity is not valid when signing a binary for the product type 'Dynamic Library'

**Comment by s84088722** [comment]
看来是还没适配xcode11实锤了,我还是装回xcode10算了

**Comment by xfdev** [comment]
你好，请问这个最后怎么解决的呢？

**Comment by xfdev** [comment]
> 在Xcode中该target的build settings 中添加"CODE_SIGNING_ALLOWED=NO", 问题解决.
来源：http://iosre.com/t/xcode-10-2/14369
