### ISSUE TITLE
新建Logos Tweak出错

### ISSUE THREAD

**Issue by updata7** [AloneMonkey/MonkeyDev#219]
错误提示如下：
`building for iOS, but linking in .tbd file (/opt/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd) built for iOS Simulator, file '/opt/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd' for architecture armv7`

选择真机连接就有这个问题，如果选模拟器，设置真机ip，然后把
`#if TARGET_OS_SIMULATOR
#error Do not support the simulator, please use the real iPhone Device.
#endif`
注释掉就可以正常安装到手机，但是插件在真机加载不成功。

新建项目，基本什么都没改，会提示这个问题，想问下为什么呢？应该如何改呢？麻烦有遇到的帮忙看看，感激不尽。

cat CydiaSubstrate.tbd 内容如下：
`---
archs:           [ armv7, armv7s, arm64, i386, x86_64 ]
platform:        ios
install-name:    /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate
current-version: 0.0.0
compatibility-version: 0.0.0
exports:
  - archs:            [ armv7, armv7s, arm64, i386, x86_64 ]
    symbols:          [ _MSDebug,
                        _MSFindSymbol, _MSGetImageByName,
                        _MSHookFunction, _MSHookMessageEx ]`

xcode Version 11.0
macOS 10.14.4
iOS 8.4.1

**Comment by JimWithJiang** [comment]
CydiaSubstrate.tbd中只留下arm64就可以了

**Comment by updata7** [comment]
可以了，非常感谢～～
