### ISSUE TITLE
遇到问题了，

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#22]
strCommand = xcodebuild -project ZYAppFactory.xcodeproj -configuration Release ARCHS=\"armv7 armv7s arm64\" build，用Xcode  执行system([strCommand UTF8String]) ，编译出来的包和直接打开Xcode运行工程的包会不一样，一个能用一个不能用，我想用Xcode 调用命令编译，上个方式结果有问题的，直接将上面的命令放在终端编译是没问题的，就是放在Xcode内部去调会有问题，请大神提示，或者有什么更好的方法吗

**Comment by AloneMonkey** [comment]
不知道你的目的是什么？  为什么要这么做，哪里有问题，而且跟这个项目没任何关系。
