### ISSUE TITLE
xcode11上monkeyApp模版导致xcode崩溃

### ISSUE THREAD

**Issue by xingzheyk** [AloneMonkey/MonkeyDev#220]
xcode11上MonkeyApp模版、LogosTweak模版，导致xcode崩溃。
不能用这两个模版创建工程，也不能打开之前创建的工程。
我不确定是否是我自己的问题，求指导。
崩溃信息如下：
Process:               Xcode [3052]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            Xcode
Version:               11.1 (15405)
Build Info:            IDEFrameworks-15405000000000000~13 (11A1027)
App Item ID:           497799835
App External ID:       832925179
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [3052]
User ID:               501

Date/Time:             2019-10-15 20:03:58.700 +0800
OS Version:            Mac OS X 10.15.1 (19B68f)
Report Version:        12
Anonymous UUID:        76221841-9174-7842-3435-E1318797CD3C

Time Awake Since Boot: 1800 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: IDEContainer - uniquing lock

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
com.apple.main-thread
ProductBuildVersion: 11A1027
ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-15403/DVTFoundation/FileTypes/DVTFileDataType.mm:156
Details:  Assertion failed: identCStr && identCStr[0]
Function: DVTPrimitiveFileDataType *_DVTGetPrimitiveFileDataTypeForIdentifierCStr_unlocked(const char *)
Thread:   <NSThread: 0x7fb905416020>{number = 1, name = main}
Hints:   
 
Backtrace:
  0   -[IDEAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in IDEKit)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   _DVTAssertionFailureHandler (in DVTFoundation)
  4   _DVTGetPrimitiveFileDataTypeForIdentifierCStr_unlocked (in DVTFoundation)
  5   _DVTGetPrimitiveFileDataTypeForIdentifier_unlocked (in DVTFoundation)
  6   _DVTCreatePrimitiveFileDataTypeForIdentifierCStr_unlocked (in DVTFoundation)
  7   _DVTGetPrimitiveFileDataTypeForIdentifierCStr_unlocked (in DVTFoundation)
  8   +[DVTFileDataType fileDataTypeFromStringRepresentation:] (in DVTFoundation)
  9   +[DVTFileDataType fileDataTypeWithIdentifier:] (in DVTFoundation)
 10   +[DVTFileDataType _fileDataTypeForFileAtPath:consideringFileContent:error:] (in DVTFoundation)
 11   +[DVTFileDataType fileDataTypeForFilePath:error:] (in DVTFoundation)
 12   DVTLazyInitAtomicDiscarding (in DVTFoundation)
 13   -[DVTFilePath cachedValueForKey:] (in DVTFoundation)
 14   -[IDEFileReference presumedFileDataType] (in IDEFoundation)
 15   -[IDEFileReference _resolveReferencedContainerExtension] (in IDEFoundation)
 16   -[IDEFileReference referencedContainerExtension] (in IDEFoundation)
 17   -[IDEContainer _locateFileReferencesRecursivelyInGroup:] (in IDEFoundation)
 18   -[IDEContainer _locateFileReferencesRecursivelyInGroup:] (in IDEFoundation)
 19   -[IDEContainer _locateFileReferencesRecursivelyInGroup:] (in IDEFoundation)
 20   -[IDEContainer _locateFileReferencesRecursively] (in IDEFoundation)
 21   __46-[IDEContainer _didReadOperationWithFilePath:]_block_invoke (in IDEFoundation)
 22   -[DVTOperation main] (in DVTFoundation)
 23   -[IDEContainer _readAsyncIfPossibleFromFilePath:error:] (in IDEFoundation)
 24   -[IDEContainer initWithFilePath:extension:workspace:options:error:] (in IDEFoundation)
 25   -[Xcode3Project initWithFilePath:extension:workspace:options:error:] (in DevToolsCore)
 26   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 (in IDEFoundation)
 27   _dispatch_client_callout (in libdispatch.dylib)
 28   _dispatch_lane_barrier_sync_invoke_and_complete (in libdispatch.dylib)
 29   DVTDispatchBarrierSync (in DVTFoundation)
 30   -[DVTDispatchLock performLockedBlock:] (in DVTFoundation)
 31   __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke (in IDEFoundation)
 32   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 33   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 34   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 35   +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] (in IDEFoundation)
 36   +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] (in IDEFoundation)
 37   -[IDEFileReference _recalculateReferencedContainer] (in IDEFoundation)
 38   -[IDEFileReference referencedContainer] (in IDEFoundation)
 39   -[IDEFileReference _resolvedFilePathDidChange:] (in IDEFoundation)
 40   __36-[IDEFileReference resolvedFilePath]_block_invoke (in IDEFoundation)
 41   __40-[DVTFilePath _notifyAssociatesOfChange]_block_invoke (in DVTFoundation)
 42   __40-[DVTFilePath _notifyAssociatesOfChange]_block_invoke.589 (in DVTFoundation)
 43   __DVT_CALLING_CLIENT_BLOCK__ (in DVTFoundation)
 44   ___DVTAsyncPerformBlockOnMainRunLoop_block_invoke (in DVTFoundation)
 45   __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ (in CoreFoundation)
 46   __CFRunLoopDoBlocks (in CoreFoundation)
 47   __CFRunLoopRun (in CoreFoundation)
 48   CFRunLoopRunSpecific (in CoreFoundation)
 49   RunCurrentEventLoopInMode (in HIToolbox)
 50   ReceiveNextEventCommon (in HIToolbox)
 51   _BlockUntilNextEventMatchingListInModeWithFilter (in HIToolbox)
 52   _DPSNextEvent (in AppKit)
 53   -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] (in AppKit)
 54   -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] (in DVTKit)
 55   -[NSApplication run] (in AppKit)
 56   NSApplicationMain (in AppKit)
 57   main (in Xcode)
 58   start (in libdyld.dylib)
 
abort() called

Application Specific Signatures:
identCStr && identCStr[0]

Thread 0 Crashed:: Dispatch queue: IDEContainer - uniquing lock
0   libsystem_kernel.dylib            0x00007fff632c545a __pthread_kill + 10
1   libsystem_pthread.dylib           0x00007fff633826cb pthread_kill + 384
2   libsystem_c.dylib                 0x00007fff6324da28 abort + 120
3   com.apple.dt.IDEKit               0x0000000109bcc499 +[IDEAssertionHandler _handleAssertionWithLogString:assertionSignature:assertionReason:extraBacktrace:] + 1276
4   com.apple.dt.IDEKit               0x0000000109bcd01d -[IDEAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] + 1143
5   com.apple.dt.DVTFoundation        0x000000010819bbe4 _DVTAssertionHandler + 619
6   com.apple.dt.DVTFoundation        0x000000010819bd9e _DVTAssertionFailureHandler + 374
7   com.apple.dt.DVTFoundation        0x000000010819bd0e _DVTAssertionFailureHandler + 230
8   com.apple.dt.DVTFoundation        0x00000001081ed51d _DVTGetPrimitiveFileDataTypeForIdentifierCStr_unlocked + 605
9   com.apple.dt.DVTFoundation        0x00000001081eef6d _DVTGetPrimitiveFileDataTypeForIdentifier_unlocked + 103
10  com.apple.dt.DVTFoundation        0x00000001081edac7 _DVTCreatePrimitiveFileDataTypeForIdentifierCStr_unlocked + 891
11  com.apple.dt.DVTFoundation        0x00000001081ed446 _DVTGetPrimitiveFileDataTypeForIdentifierCStr_unlocked + 390
12  com.apple.dt.DVTFoundation        0x00000001081f08d5 +[DVTFileDataType fileDataTypeFromStringRepresentation:] + 636
13  com.apple.dt.DVTFoundation        0x00000001081f0d8e +[DVTFileDataType fileDataTypeWithIdentifier:] + 17
14  com.apple.dt.DVTFoundation        0x00000001081f3e32 +[DVTFileDataType _fileDataTypeForFileAtPath:consideringFileContent:error:] + 381
15  com.apple.dt.DVTFoundation        0x00000001081f4aec +[DVTFileDataType fileDataTypeForFilePath:error:] + 56
16  com.apple.dt.DVTFoundation        0x00000001080b8389 DVTLazyInitAtomicDiscarding + 33
17  com.apple.dt.DVTFoundation        0x000000010802d14e -[DVTFilePath cachedValueForKey:] + 467
18  com.apple.dt.IDEFoundation        0x0000000108ecd870 -[IDEFileReference presumedFileDataType] + 153
19  com.apple.dt.IDEFoundation        0x0000000108ecdf96 -[IDEFileReference _resolveReferencedContainerExtension] + 33
20  com.apple.dt.IDEFoundation        0x0000000108ece34b -[IDEFileReference referencedContainerExtension] + 466
21  com.apple.dt.IDEFoundation        0x0000000108f3be67 -[IDEContainer _locateFileReferencesRecursivelyInGroup:] + 314
22  com.apple.dt.IDEFoundation        0x0000000108f3bf28 -[IDEContainer _locateFileReferencesRecursivelyInGroup:] + 507
23  com.apple.dt.IDEFoundation        0x0000000108f3bf28 -[IDEContainer _locateFileReferencesRecursivelyInGroup:] + 507
24  com.apple.dt.IDEFoundation        0x0000000108f3c38a -[IDEContainer _locateFileReferencesRecursively] + 133
25  com.apple.dt.IDEFoundation        0x0000000108f4796b __46-[IDEContainer _didReadOperationWithFilePath:]_block_invoke + 251
26  com.apple.dt.DVTFoundation        0x00000001081b78a1 -[DVTOperation main] + 75
27  com.apple.dt.IDEFoundation        0x0000000108f47c82 -[IDEContainer _readAsyncIfPossibleFromFilePath:error:] + 327
28  com.apple.dt.IDEFoundation        0x0000000108f3fa00 -[IDEContainer initWithFilePath:extension:workspace:options:error:] + 1419
29  com.apple.Xcode.DevToolsCore      0x0000000120834e64 -[Xcode3Project initWithFilePath:extension:workspace:options:error:] + 1314
30  com.apple.dt.IDEFoundation        0x0000000108f3e78e __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke_2 + 1008
31  libdispatch.dylib                 0x00007fff6312650e _dispatch_client_callout + 8
32  libdispatch.dylib                 0x00007fff63132567 _dispatch_lane_barrier_sync_invoke_and_complete + 60
33  com.apple.dt.DVTFoundation        0x00000001081e7c50 DVTDispatchBarrierSync + 208
34  com.apple.dt.DVTFoundation        0x00000001081bf078 -[DVTDispatchLock performLockedBlock:] + 64
35  com.apple.dt.IDEFoundation        0x0000000108f3e1fa __82+[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:]_block_invoke + 223
36  com.apple.dt.DVTFoundation        0x000000010805b834 __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke + 217
37  com.apple.dt.DVTFoundation        0x0000000108192b11 -[DVTModelGraphTransactionScope performTransaction:] + 66
38  com.apple.dt.DVTFoundation        0x000000010805b739 -[DVTModelObjectGraph performBlockCoalescingModelChanges:] + 146
39  com.apple.dt.IDEFoundation        0x0000000108f3dec1 +[IDEContainer _retainedContainerAtFilePath:fileDataType:workspace:options:error:] + 1569
40  com.apple.dt.IDEFoundation        0x0000000108f3d86c +[IDEContainer retainedContainerAtFilePath:fileDataType:workspace:error:] + 88
41  com.apple.dt.IDEFoundation        0x0000000108ecec0a -[IDEFileReference _recalculateReferencedContainer] + 564
42  com.apple.dt.IDEFoundation        0x0000000108ecf415 -[IDEFileReference referencedContainer] + 67
43  com.apple.dt.IDEFoundation        0x0000000108ecd5be -[IDEFileReference _resolvedFilePathDidChange:] + 154
44  com.apple.dt.IDEFoundation        0x0000000108ecd318 __36-[IDEFileReference resolvedFilePath]_block_invoke + 77
45  com.apple.dt.DVTFoundation        0x000000010802e7b5 __40-[DVTFilePath _notifyAssociatesOfChange]_block_invoke + 240
46  com.apple.dt.DVTFoundation        0x000000010802e9da __40-[DVTFilePath _notifyAssociatesOfChange]_block_invoke.589 + 11
47  com.apple.dt.DVTFoundation        0x00000001081e59ba __DVT_CALLING_CLIENT_BLOCK__ + 7
48  com.apple.dt.DVTFoundation        0x00000001081ea3d5 ___DVTAsyncPerformBlockOnMainRunLoop_block_invoke + 115
49  com.apple.CoreFoundation          0x00007fff2bbfbd4b __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
50  com.apple.CoreFoundation          0x00007fff2bbbef8d __CFRunLoopDoBlocks + 379
51  com.apple.CoreFoundation          0x00007fff2bbbe701 __CFRunLoopRun + 1257
52  com.apple.CoreFoundation          0x00007fff2bbbdf93 CFRunLoopRunSpecific + 499
53  com.apple.HIToolbox               0x00007fff2a747a0d RunCurrentEventLoopInMode + 292
54  com.apple.HIToolbox               0x00007fff2a747659 ReceiveNextEventCommon + 356
55  com.apple.HIToolbox               0x00007fff2a7474d7 _BlockUntilNextEventMatchingListInModeWithFilter + 64
56  com.apple.AppKit                  0x00007fff28de3d24 _DPSNextEvent + 990
57  com.apple.AppKit                  0x00007fff28de2a94 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
58  com.apple.dt.DVTKit               0x00000001087ee09b -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 390
59  com.apple.AppKit                  0x00007fff28ddd234 -[NSApplication run] + 658
60  com.apple.AppKit                  0x00007fff28dcf0dd NSApplicationMain + 777
61  com.apple.dt.Xcode                0x0000000107eccefd main + 541
62  libdyld.dylib                     0x00007fff631762e5 start + 1

**Comment by xingzheyk** [comment]
解决了，执行以下命令：
 /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

**Comment by VenpleD** [comment]
xcode 10.3没有了模板要怎么解决啊，系统是macOS是10.15.4
