### ISSUE TITLE
xcode 11.2   运行几次正常后会出现dpkg安装失败问题   dpkg: error  有大佬遇到的么

### ISSUE THREAD

**Issue by Yongle-Fu** [AloneMonkey/MonkeyDev#223]
dpkg: error processing archive /var/root/MonkeyDevPackages/xxx_0.1-1_iphoneos-arm.deb (--install):
 corrupted filesystem tarfile in package archive: unsupported PAX tar header type 'x'

**Comment by Lessica** [comment]
这里也遇到过了。

经过检查，原因是 [`/opt/MonkeyDev/bin/md`](https://github.com/AloneMonkey/MonkeyDev/blob/c37b5cc5e9a4184d80eb18fb9ae8c48bb8689442/bin/md#L487) 使用 macOS 自带的 tar，即 **bsdtar**，而越狱后 Cydia 提供的 *Tape Archive* 和 *Debian Packager* 是 GNU dpkg 和 **gnutar**，二者存在不完全兼容的情况。

解决方法：

使用 Homebrew 安装 **gnu-tar**

```bash
brew install gnu-tar
```

将 `/opt/MonkeyDev/bin/md` 第 487 行

```bash
tar -cLpz --disable-copyfile --exclude ".*" "$@" -f "$outputDir/$tarName.tar.gz" * || \
	panic $? "Failed to create $tarName archive"
```

替换为

```bash
gtar -chpz --exclude ".*" "$@" -f "$outputDir/$tarName.tar.gz" * || \
	panic $? "Failed to create $tarName archive"
```

**Comment by KingSun0** [comment]
厉害
