### ISSUE TITLE
为了实现自动化使用monkeyDev，所以想用命令行来调用

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#23]
为了自动化调用monkeyDev，所以想用命令行来调用，但是发现用命令行调用工程 xcodebuild编译出现的包和打开xcode编译出来的包结果不一样，是什么原因，有什么解决办法吗，请指教

**Comment by zhoupenghao** [comment]
用命令行来操作，使用monkey dev，这里使用命令行编译出来的包安装后会闪退，打开xcode直接build结果就OK的，困扰已久，求指导

**Comment by AloneMonkey** [comment]
不能用shell？

**Comment by zhoupenghao** [comment]
不知道是不是我哪里配置不对，还是如何，命令build  之后的ipa包和xcode 直接build的包大小不一致，命令编译的安装后会闪退

**Comment by zhoupenghao** [comment]
不知道原因，比较困扰

**Comment by zhoupenghao** [comment]
未越狱的设备

**Comment by zhoupenghao** [comment]
大概是流程是这样的，将破壳的IPA包放至TargetApp文件夹下，执行build操作，编译完成后，使用createIPA.command，生成target.IPA包

我这出现的问题是，通过打开xcode进行build  生成的.app，createIPA.command出来的IPA包没问题，通过命令行build生成的.app，再createIPA.command的IPA包，两个包大小不同，后者可以安装，启动时会闪退

**Comment by AloneMonkey** [comment]
为什么要用system，直接shell脚本不行？

**Comment by zhoupenghao** [comment]
我试试看吧，结果会有异同吗
