### ISSUE TITLE
process launch failed

### ISSUE THREAD

**Issue by yasencoder** [AloneMonkey/MonkeyDev#230]
您好，感谢您提供的开源项目。但是在使用的时候遇到了以下问题：

<img width="1440" alt="截屏2020-01-0817 38 36" src="https://user-images.githubusercontent.com/16420441/71967065-b2a87600-323d-11ea-8a2b-83406ff10382.png">

运行项目的时候，Xcode 提示以下信息，app启动失败

has denied the launch request.
Internal launch error: process launch failed: Unspecified

**Comment by TralyFang** [comment]
我也不知道啊，怎么解决啊

**Comment by bhuhzy** [comment]
Could u send me a direct link if it’s ok by u.. I kinda always get d wrong links..
