### ISSUE TITLE
我用macbookPro终端安装出错，开了科学上网也不行。

### ISSUE THREAD

**Issue by WCMYCML** [AloneMonkey/MonkeyDev#242]
$ sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-install)"

curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

**Comment by xp9477** [comment]
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7891
终端中使用本地代理

**Comment by KeepCoding9494** [comment]
大佬 可不可以详细点

**Comment by xp9477** [comment]
> 大佬 可不可以详细点

访问[https://www.ipaddress.com](可能要挂代理)，输入raw.githubusercontent.com查询
将显示的IP加入hosts
`sudo vim /etc/hosts`
在后面追加
`x.x.x.x(查询到的ip) raw.githubusercontent.com`
保存后刷新DNS
`sudo killall -HUP mDNSResponder`
再使用安装命令就可以了
`sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-install)"`
我昨天刚在一台新电脑上安装，可用

**Comment by xiaochaoyang** [comment]
> > 大佬 可不可以详细点
> 
> 访问[https://www.ipaddress.com](%E5%8F%AF%E8%83%BD%E8%A6%81%E6%8C%82%E4%BB%A3%E7%90%86)，输入raw.githubusercontent.com查询
> 将显示的IP加入hosts
> `sudo vim /etc/hosts`
> 在后面追加
> `x.x.x.x(查询到的ip) raw.githubusercontent.com`
> 保存后刷新DNS
> `sudo killall -HUP mDNSResponder`
> 再使用安装命令就可以了
> `sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-install)"`
> 我昨天刚在一台新电脑上安装，可用

亲测可用，给大佬点赞

**Comment by WCMYCML** [comment]
> > 大佬 可不可以详细点
> 
> 访问[https://www.ipaddress.com](%E5%8F%AF%E8%83%BD%E8%A6%81%E6%8C%82%E4%BB%A3%E7%90%86)，输入raw.githubusercontent.com查询
> 将显示的IP加入hosts
> `sudo vim /etc/hosts`
> 在后面追加
> `x.x.x.x(查询到的ip) raw.githubusercontent.com`
> 保存后刷新DNS
> `sudo killall -HUP mDNSResponder`
> 再使用安装命令就可以了
> `sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-install)"`
> 我昨天刚在一台新电脑上安装，可用
嗯谢谢大佬提供详细的步骤学习了，
