### ISSUE TITLE
Xcode monkeyDev配置问题

### ISSUE THREAD

**Issue by xiaochaoyang** [AloneMonkey/MonkeyDev#243]
我这边用monkeyDev创建了一个demo，但是dylib库始终签名不成功，
报错如下：
<img width="887" alt="截屏2020-05-05 下午8 17 55" src="https://user-images.githubusercontent.com/16273178/81065361-e3f43280-8f0d-11ea-865b-d164364a4be6.png">
我的配置如下：
<img width="801" alt="截屏2020-05-05 下午8 18 05" src="https://user-images.githubusercontent.com/16273178/81065385-ef475e00-8f0d-11ea-9979-98c5eeb40407.png">
<img width="871" alt="截屏2020-05-05 下午8 18 15" src="https://user-images.githubusercontent.com/16273178/81065388-f1112180-8f0d-11ea-9d48-9ed0d1e8f020.png">
dylib库没有配置签名的地方，有人知道怎么解决么

**Comment by akzhang** [comment]
我也是同样的问题， 请问解决了吗？

**Comment by akzhang** [comment]
在Xcode中该target的build settings 中添加"CODE_SIGNING_ALLOWED=NO", 这样试试
![image](https://user-images.githubusercontent.com/4043933/81533752-51361680-9399-11ea-89ef-65c452516a22.png)

**Comment by xiaochaoyang** [comment]
> 在Xcode中该target的build settings 中添加"CODE_SIGNING_ALLOWED=NO", 这样试试
> ![image](https://user-images.githubusercontent.com/4043933/81533752-51361680-9399-11ea-89ef-65c452516a22.png)

确实可以，多谢大佬
