### ISSUE TITLE
macos10.13中_dyld_get_all_image_infos不再导出了

### ISSUE THREAD

**Issue by rozbo** [AloneMonkey/MonkeyDev#25]
这本来没有什么问题。。。但是我们使用了`substrate`作为hook框架，它的`libsubstitute.dylib`里面恰好引用了这个api，所以10.13的mac 插件是无法运行的。

你有其他的办法吗？
如果没有的话，就全当给后来的兄弟们提个醒了，暂时不要升级到macos10.13

**Comment by luckycoder-git** [comment]
嗯，谢谢提醒，我是10.12.6 的MacOS！

**Comment by rozbo** [comment]
fixed by #31
