### ISSUE TITLE
请问一下，我需要注入自己的库，需要一些权限的申请

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#26]
请问一下，我需要注入自己的库，需要一些权限的申请方面，正常使用库是修改plist，比如http之类的，monkey dev应该怎么使用

**Comment by AloneMonkey** [comment]
打开应用的下的Info.plist文件编辑。

**Comment by zhoupenghao** [comment]
修改monkeydev的info不行的是吗，修改是在注入之前吗

**Comment by AloneMonkey** [comment]
要直接修改应用的Info.plist

**Comment by zhoupenghao** [comment]
在注入之前先修改应用的info

**Comment by AloneMonkey** [comment]
就是修改你放入的应用里面的Info.plist

**Comment by zhoupenghao** [comment]
monkeyDev是怎么处理这个的

**Comment by AloneMonkey** [comment]
没处理，自己加。

**Comment by zhoupenghao** [comment]
这样，现在有个疑问，在使用monkeyDev的情况下，哪个步骤去修改

**Comment by AloneMonkey** [comment]
放入目标应用的时候就修改应用里面的Info.plist

**Comment by zhoupenghao** [comment]
放入目标应用的时候就修改应用里面的Info.plist


不是特别理解您的意思，我在使用monkeyDev之前先将ipa包进行解压，修改info.plist，重新打包成ipa  再进行使用monkeyDev，还是说在使用monkeyDev的时候可以进行这样的操作

**Comment by AloneMonkey** [comment]
我在使用monkeyDev之前先将ipa包进行解压，把app文件夹放到TargetApp下面，删除ipa文件，修改app文件夹下面的Info.plist
