### ISSUE TITLE
Big Sur Beta10下无法正常运行

### ISSUE THREAD

**Issue by icubic3** [AloneMonkey/MonkeyDev#262]
https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/
在beta10下有这个问题：
New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

这导致在beta10下运行起来会报错：找不到/usr/lib/libstdc++.dylib
想问下有什么好的解决方法吗？谢谢

**Comment by liurenqiu520** [comment]
https://github.com/devdawei/libstdc-
运行对应版本的sh文件即可。

**Comment by icubic3** [comment]
感谢解答 不过我看在最新的Big Sur下已经能正常跑了 应该不存在问题了
