### ISSUE TITLE
集成Reveal 1.x版的framework出错，提示Could not inspect the application package

### ISSUE THREAD

**Issue by wonderffee** [AloneMonkey/MonkeyDev#27]
本来这个问题已经在群里问过，没人回应，在这里再试试运气吧。

首先要说明的是用MonkeyDev自带的 RevealServer.framework 测试真机运行完全没问题。但因为自己买的是1.x版本的Reveal，所以想用1.x版本的framework

我将Reveal 1.x版的framework放在/opt/MonkeyDev/frameworks 路径下面，build phase里也删掉了原来的RevealServer.framework，添加了1.x版本的 Reveal.framework。

结果编译没有问题，copy数据与资源也没有问题，就是要在启动前Xcode突然给了一个提示：Could not inspect the application package

**Comment by wonderffee** [comment]
看了一下Xcode上的Device log，发现安装失败时一条关键日志：
Failed to load Info.plist from bundle at path /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.9cvUx1/extracted/xxxx.app/Frameworks/Reveal.framework}
对比了一下 Reveal.framework 和 RevealServer.framework，发现后者的文件夹下有Info.plist，前者没有，猜测是因为Reveal.framework是旧版的在新版Xcode中不兼容
因而Reveal.framework应该是不能用了。于是就删除了它，注意要删除干净，/opt/MonkeyDev/frameworks路径下和Xcode左侧的文件列表中都要删除，要不然会重复出现上面的提示。

退而求其次，我尝试了文章[iOS开发中集成Reveal](http://blog.devzeng.com/blog/ios-reveal-integrating.html)里面使用libReveal.dylib的方法，看文末(2)Reveal连接真机 那一部分，libReveal.dylib要添加到非dylib的那个target里，并且通过Build Phases里面的Copy Bundle Resources方式添加，在启动app后运行到断点后连续执行两条命令reveal_load_dev 和reveal_start以启动Reveal调试。
测试可以成功。

**Comment by AloneMonkey** [comment]
你那个Reveal.framework应该是个静态库，你要放在/opt/MonkeyDev/Librarys下面。

**Comment by wonderffee** [comment]
估计是，后面我再测试一下吧

**Comment by wonderffee** [comment]
测试可以用，但好像没必要放在 /opt/MonkeyDev/Librarys 下面，重点是要添加 -ObjC -lz -framework Reveal 选项
