### ISSUE TITLE
貌似不支持xib

### ISSUE THREAD

**Issue by wonderffee** [AloneMonkey/MonkeyDev#28]
文档里说过可以用storyboard，我试过的确可以，但是如果用xib的话，将xib文件添加进copy  bundles resources, Xcode在编译成功后，同时也是install之前的时候一定会报错：The file “xxxapp” couldn’t be opened because you don’t have permission to view it.
将xib文件从copy  bundles resources中删除就不会报错了，但好像没法用这个xib文件了
问题必现
有办法支持吗？

**Comment by wonderffee** [comment]
用framework解决了，本来想用文档里面提示的bundle，结果发现Xcode8里创建不了bundle😅

**Comment by AloneMonkey** [comment]
新版修复了这个问题，你再试下。

**Comment by wonderffee** [comment]
晚上试一下，看了一下代码对比，好像也就是加了一些空格，然后就是有一个文件重命名再重命名回来，这样就能解决xib加载的问题了？如果不嫌麻烦的话可以说说原理

**Comment by AloneMonkey** [comment]
空格无关，Info.plist文件没替换

**Comment by AloneMonkey** [comment]
你xib的问题解决了吗？

**Comment by wonderffee** [comment]
还木有，这几天网络风声紧尽搞网络问题去了。。。

**Comment by wonderffee** [comment]
确认xib加载的问题解决，以后使用xib更方便了
另外一个无关紧要的问题，测试了一下如果使用images.xcassets，因担心与原安装包里的images.car冲突改名成了main.xcassets，也在copy bundles resources中添加，运行后发现安装包没有生成main.car文件，更无从加载里面的图片，这个是故意忽略了还是Xcode只允许一个xcassets文件的存在？
