### ISSUE TITLE
iOS 14.5运行报错

### ISSUE THREAD

**Issue by key-start** [AloneMonkey/MonkeyDev#280]
![image](https://user-images.githubusercontent.com/12524077/116334243-766ca080-a807-11eb-9eed-25bb11ecb164.png)

**Comment by freedom6xiaobai** [comment]
i https://github.com/facebook/fishhook/pull/83/files

**Comment by key-start** [comment]
> i https://github.com/facebook/fishhook/pull/83/files

谢谢，我那天也是根据这个pull请求解决的问题
