### ISSUE TITLE
无法编译问题

### ISSUE THREAD

**Issue by wenshao1018** [AloneMonkey/MonkeyDev#3]
1、Xcode8.3.3在App里面增加动态库的依赖直接报2个错误
1.1cp: /Users/XXX/Library/Developer/Xcode/DerivedData/MonkeyDev-eiuqhtpfyhdozadjrsuiqfdigrdj/Build/Products/Debug-iphoneos/libMonkeyDevDylib.dylib: No such file or directory

1.2Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

2、Xcode不添加动态库依赖，能编译成功，但是无法运行，直接崩溃。报错原因如下。
dyld`__abort_with_payload:
    0x1017be8b4 <+0>:  mov    x16, #0x209
    0x1017be8b8 <+4>:  svc    #0x80
->  0x1017be8bc <+8>:  b.lo   0x1017be8d4               ; <+32>
    0x1017be8c0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1017be8c4 <+16>: mov    x29, sp
    0x1017be8c8 <+20>: bl     0x1017be100               ; cerror_nocancel
    0x1017be8cc <+24>: mov    sp, x29
    0x1017be8d0 <+28>: ldp    x29, x30, [sp], #0x10
    0x1017be8d4 <+32>: ret

**Comment by AloneMonkey** [comment]
是不是没有增加依赖: [Q&A](https://github.com/AloneMonkey/MonkeyDev/wiki/Q&A#two)
如果加了依赖，单独编译动态库报错吗？

**Comment by tepmnthar** [comment]
Xcode 8.3.3 不加动态库依赖崩溃信息一样
不过加了之后我这的编译报错是
```
/Users/TEP/Documents/playground/TestMonkeyApp/TestMonkeyAppDylib/TestMonkeyAppDylib.m:14:9: fatal error: 'CaptainHook/CaptainHook.h' file not found
#import <CaptainHook/CaptainHook.h>
        ^
1 error generated.
```
另外，不知道为什么我的 build settings 里面没有那些选项

**Comment by AloneMonkey** [comment]
头文件没有找到是因为最新theos没有安装在/opt/theos 
刚刚更新了下直接把头文件放项目里面了，你在bin目录下面执行 sudo ./md-update 更新一下。

**Comment by tepmnthar** [comment]
哦，我按照官方说明装 ~/theos 里了。。
感谢大佬
