### ISSUE TITLE
动态库编译注入后提示：no matching architecture in universal wrapper

### ISSUE THREAD

**Issue by ammrwu** [AloneMonkey/MonkeyDev#33]
Termination Description: DYLD, Library not loaded: @executable_path/jjjj.dylib | Referenced from: /var/containers/Bundle/Application/ADE3107E-C934-4F67-9EEF-EC54689C39DE/WeChat.app/WeChat | Reason: no suitable image found.  Did find: | /var/containers/Bundle/Application/ADE3107E-C934-4F67-9EEF-EC54689C39DE/WeChat.app/jjjj.dylib: no matching architecture in universal wrapper | /private/var/containers/Bundle/Application/ADE3107E-C934-4F67-9EEF-EC54689C39DE/WeChat.app/jjjj.dylib: no matching architecture in universal wrapper
--------------------------------------
otool -L jjjj.dylib
看不到arm64 armv7这些信息
但是在architechtures里面都选了的。。。

**Comment by ammrwu** [comment]
otool 查看是这样的
ammrwudeMacBook-Pro:Release-iphonesimulator ammrwu$ otool -L jjjj.dylib
jjjj.dylib:
	/Library/MobileSubstrate/DynamicLibraries/jjjj.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.7.47)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.55.0)
	/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1349.56.0)

**Comment by AloneMonkey** [comment]
真机

**Comment by ammrwu** [comment]
没有连接手机，是products里面找到dylib，然后再用yololib注入的
是直接新建的logos tweak 直接编译 我看别人的动态库都是有armv7和arm64信息的，类似下面的：
ammrwudeMacBook-Pro:wscq ammrwu$ otool -L ./wssj.dylib （别人的）
./wssj.dylib (architecture armv7):
	/usr/lib/wssj.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.2.0)
	@executable_path/Frameworks/libsubstrate.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore (compatibility version 1.0.0, current version 603.1.30)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1349.55.0)
	/System/Library/Frameworks/CoreMotion.framework/CoreMotion (compatibility version 1.0.0, current version 2101.0.62)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.54.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.7.47)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/System/Library/Frameworks/Security.framework/Security (compatibility version 1.0.0, current version 0.0.0)
./wssj.dylib (architecture arm64):
	/usr/lib/wssj.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.2.0)
	@executable_path/Frameworks/libsubstrate.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore (compatibility version 1.0.0, current version 603.1.30)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1349.55.0)
	/System/Library/Frameworks/CoreMotion.framework/CoreMotion (compatibility version 1.0.0, current version 2101.0.62)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.54.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.7.47)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)

但是我的我编译出来的就没有，是哪里设置不对么
ammrwudeMacBook-Pro:Release-iphonesimulator ammrwu$ otool -L jjjj.dylib（我的）
jjjj.dylib:
/Library/MobileSubstrate/DynamicLibraries/jjjj.dylib (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.7.47)
/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.55.0)
/Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
/usr/lib/libSystem.dylib (compatibility version 1.0.0, current version 1238.50.2)
/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1349.56.0)
然后注入之后就提示no matching architecture in universal wrapper

**Comment by AloneMonkey** [comment]
选手机编译、不是选模拟器

**Comment by ammrwu** [comment]
thank u very very very much!!!!!!
