### ISSUE TITLE
这是因为input的包有问题吗

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#34]
fatal error: lipo: can't open input file: /Users/mac/Desktop/webapp/webapp/TargetApp/xxx.app/xxx (No such file or directory)
fatal error: lipo: can't open input file: /Users/mac/Desktop/webapp/webapp/TargetApp/xxx.app /xxx(No such file or directory)
fatal error: lipo: can't open input file: /Users/mac/Desktop/webapp/webapp/TargetApp/xxx.app/xxx (No such file or directory)
has arm7 arch? false
has arm64 arch? false
is fat file? true

**Comment by AloneMonkey** [comment]
自己看下有没有这个文件

**Comment by zhoupenghao** [comment]
还有个问题，用命令执行编译monkeyDev怎么选择provision

**Comment by AloneMonkey** [comment]
Xcode选

**Comment by zhoupenghao** [comment]
不打开xcode，用命令monkeyDev  provision不能选择吗？

**Comment by zhoupenghao** [comment]
这块内容能不能升级一下，动态设置bundleID、选择provision，等等，可以直接使用命令行完成，打开xcode编译release  要改这些多一些应用，操作上步骤会增加不少，可以直接用命令来操作就可以减少很多实际操作了
