### ISSUE TITLE
MonkeyDev 什么时候支持Xcode15

### ISSUE THREAD

**Issue by Lunction** [AloneMonkey/MonkeyDev#348]
libc++库导入不进去

**Comment by anbabyQAQ** [comment]
同样是 libc++库导入不进去,整个Runtimes文件拷贝进去也不行
<img width="1175" alt="image" src="https://github.com/AloneMonkey/MonkeyDev/assets/19640459/4a6bc197-85ee-48f2-99ee-15bf2fdc8c3e">

**Comment by Lunction** [comment]
> 同样是 libc++库导入不进去,整个Runtimes文件拷贝进去也不行 <img alt="image" width="1175" src="https://user-images.githubusercontent.com/19640459/274558573-4a6bc197-85ee-48f2-99ee-15bf2fdc8c3e.png">

降到14.3.1版本解决了

**Comment by mengwq** [comment]
可以在Other linker Flags中删掉/usr/lib/libc++.dylib和/usr/lib/libstdc++.dylib就可以了

**Comment by camenling** [comment]
> 可以在Other linker Flags中删掉/usr/lib/libc++.dylib和/usr/lib/libstdc++.dylib就可以了

这两个库没有在用?

**Comment by LiuSky** [comment]
> > 可以在Other linker Flags中删掉/usr/lib/libc++.dylib和/usr/lib/libstdc++.dylib就可以了
> 
> 这两个库没有在用?

不行的，还有在用。我也遇到了这个问题。只能降级到14了

**Comment by LiuSky** [comment]
已解决https://github.com/AloneMonkey/MonkeyDev/issues/349
