### ISSUE TITLE
libc++库 适配macOs Sonoma14.0  Xcode15

### ISSUE THREAD

**Issue by anbabyQAQ** [AloneMonkey/MonkeyDev#349]
大佬们 分享下[libc++库 适配macOs Sonoma14.0  Xcode15]是咋搞定的 [爱心]

**Comment by LZRight123** [comment]
mark 一下

**Comment by 546200350** [comment]
m

**Comment by ju4tin** [comment]
好像就老的fishhook依赖libstdc++,你替换一下最新的fishhook,就不用依赖libstdc++了

**Comment by anbabyQAQ** [comment]
确实如此,之前已将最新的fishhook替换掉monkeydev中的fishhook ，但一直没删除配置文件Other Linker Flags中libc++库，把它删除掉 ，在导入下 libarclite_iphoneos.a静态库到/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc下 就适配了xcode15了 ，感谢大佬提醒~ @ju4tin 

![Uploading image.png…]()

**Comment by anbabyQAQ** [comment]
<img width="869" alt="image" src="https://github.com/AloneMonkey/MonkeyDev/assets/19640459/a324c2bb-c632-4101-8779-2682b4c4f6e5">
<img width="1243" alt="image" src="https://github.com/AloneMonkey/MonkeyDev/assets/19640459/f6faebdc-32ca-4b2c-a556-03ea8a0df04d">

下载 https://github.com/kamyarelyasi/Libarclite-Files 中的libarclite_iphoneos.a就可以嘞

**Comment by ju4tin** [comment]
> <img alt="image" width="869" src="https://user-images.githubusercontent.com/19640459/275460989-a324c2bb-c632-4101-8779-2682b4c4f6e5.png"> <img alt="image" width="1243" src="https://user-images.githubusercontent.com/19640459/275461173-f6faebdc-32ca-4b2c-a556-03ea8a0df04d.png">
> 下载 https://github.com/kamyarelyasi/Libarclite-Files 中的libarclite_iphoneos.a就可以嘞

其实你把最低版本号支持调整到11.0,就不用依赖arc库了

**Comment by AICoderTudou** [comment]
mark

**Comment by hootigger** [comment]
mark

**Comment by shevakuilin** [comment]
mark

**Comment by shadow-boy** [comment]
mark
