### ISSUE TITLE
shirft + command + i 编译  xcode9.1   下createIPA无法安装

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#35]
The application does not have a valid signature.iPhone6
6plus可以

**Comment by zhoupenghao** [comment]
相同的ipa，使用ios-app-signer-master  重签没问题

**Comment by zhoupenghao** [comment]
嗯，多种方式编译都是这样，生成的同一个ipa   6plus可以装，6不行，The application does not have a valid signature都无法安装成功，试过多个之前下载的可以使用的破壳ipa重签都是这个结果，于是我尝试ios-app-signer-master 重签没问题，具体原因不解，provision使用确认没问题，在signer下也是选择同样的但是可以完成不同型号以及设备的安装，已发布的fir   其他测试人员的设备均可，monkeyDev不知为何不行

**Comment by zhoupenghao** [comment]
之前是可以的

**Comment by AloneMonkey** [comment]
直接Xcode run在iPhone6的机器上面呢

**Comment by zhoupenghao** [comment]
直接run iPhone6上是可以的，release包不行，直接run或者debug，然后createIPA也装不了

**Comment by zhoupenghao** [comment]
目前是部分机型可以，上传到fir上   其他测试人员反馈的结果是部分手机可以装

**Comment by AloneMonkey** [comment]
这个我也没法定位问题了

**Comment by AloneMonkey** [comment]
最好看下错误日志啥的

**Comment by zhoupenghao** [comment]
电脑不在边上，想重新装一台新电脑log出来的，/Users/zph_haoge/Library/Developer/Xcode/DerivedData/monkey-gqxibarjpverytfpdpkoziomovdu/Build/Intermediates.noindex/monkey.build/Debug-iphoneos/monkeyDylib.build/Script-ACF588321FB207D100BBD98D.sh: line 2: /opt/MonkeyDev/bin/md: No such file or directory    新电脑编译报这个错误是什么原因

**Comment by zhoupenghao** [comment]
#!/bin/sh
/opt/MonkeyDev/bin/md --xcbp-logos
应该是这个执行出错了

**Comment by zhoupenghao** [comment]
打开工程后，选择 generic iOS device 后shift command k,shift command I,编译完成后，createIPA

**Comment by zhoupenghao** [comment]
编译release没有log，应该怎么判断是哪里出现的问题呢，还是不能安装所以机型

**Comment by AloneMonkey** [comment]
安装失败时候的错误日志呢

**Comment by AloneMonkey** [comment]
直接选debug或release然后run， run完之后createIPA试试

**Comment by zhoupenghao** [comment]
好的我重新试试，目前好像类似：

打开工程后，选择 generic iOS device  编译release包，或者xcodebuild -project /path/XXX.xcodeproj -configuration Release ARCHS="armv7 armv7s arm64" build 似乎默认选择了一个支持arm，其他的就无法支持了

**Comment by AloneMonkey** [comment]
警告无关，要看App installation failed ，The application does not have a valid signature安装的时候console.app里面的签名错误日志。

**Comment by zhoupenghao** [comment]
App installation failed ，The application does not have a valid signature安装的时候console.app里面的签名错误日志     
这个日志要在哪里查看

**Comment by zhoupenghao** [comment]
我用的createIPA   然后  用xcode安装失败

**Comment by AloneMonkey** [comment]
xcode - windows - devide 或者 console.app

**Comment by zhoupenghao** [comment]
Nov  9 10:04:46 haoge-iPhone securityd[91] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Nov  9 10:04:46 haoge-iPhone securityd[91] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Nov  9 10:04:46 haoge-iPhone installd[2243] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Nov  9 10:04:47 haoge-iPhone securityd[91] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Nov  9 10:04:47 haoge-iPhone securityd[91] <Error>:  secTaskDiagnoseEntitlements MISSING keychain entitlements: no stored taskRef found
Nov  9 10:04:47 haoge-iPhone installd[2243] <Error>:  SecTrustEvaluate  [leaf IssuerCommonName SubjectCommonName]
Nov  9 10:04:47 haoge-iPhone installd[2243] <Error>: 0x16e2d3000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 142: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.xrVJLv/extracted/Payload/webapp.app/Frameworks/CYPlatform_SFRZ.framework : 0xe8008019 (The application does not have a valid signature.)
Nov  9 10:04:47 haoge-iPhone installd[2243] <Error>: 0x16e2d3000 -[MIInstaller performInstallationWithError:]: Verification stage failed
Nov  9 10:04:47 haoge-iPhone mobile_installation_proxy[2235] <Error>: 0x16e2d3000 __MobileInstallationInstallForLaunchServices_block_invoke222: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.xrVJLv/extracted/Payload/webapp.app/Frameworks/CYPlatform_SFRZ.framework : 0xe8008019 (The application does not have a valid signature.)" UserInfo={LibMISErrorNumber=-402620391, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=142, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.xrVJLv/extracted/Payload/webapp.app/Frameworks/CYPlatform_SFRZ.framework : 0xe8008019 (The application does not have a valid signature.)}
Nov  9 10:04:47 haoge-iPhone mobile_installation_proxy[2235] <Error>: 0x16e087000 handle_install: Installation failed: Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620391, ErrorDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.xrVJLv/extracted/Payload/webapp.app/Frameworks/CYPlatform_SFRZ.framework : 0xe8008019 (The application does not have a valid signature.)}
Nov  9 10:04:48 haoge-iPhone backupd[2234] <Warning>: INFO: Creating new snapshot: 0C0FA7FF-B1A5-4789-BC80-2E1DE39889F4
Nov  9 10:04:49 haoge-iPhone backupd[2234] <Warning>: Opened /System/Library/PrivateFrameworks/AirTrafficDevice.framework/AirTrafficDevice
Nov  9 10:04:49 haoge-iPhone networkd[93] <Notice>: -[NETAWDManager reportStats:metricID:] server 0x1256164d0, container 0x125651ca0, metrid 2686983, successfully reported:
	<AWDLibnetcoreTCPConnectionReport: 0x12553c380> {
	    cellularFallbackReport =     {
	        dataUsageSnapshotsAtNetworkEvents =         (
	                        {
	                bytesIn = 9200;
	                bytesOut = 2200;
	            }
	        );
	        "fallbackTimer_msecs" = 0;
	        fellback = 0;
	        networkEvents =         (
	            "NETWORK_EVENT_DATA_STALL_AT_APP_LAYER"
	        );
	        "timeToNetworkEvents_msecs" =         (
	            3203
	        );
	    };
	    clientIdentifier = itunesstored;
	    connectionStatisticsReport =     {
	        DNSAnswersCached = 0;
	        "DNSResolvedTime_msecs" = 16;
	        RTTvariance = 5;
	        "appDataStallTimer_msecs" = 3;
	        appReportingDataStallCount = 1;
	        "bestRTT_msecs" = 12;
	        betterRouteEventCount = 0;
	        bytesDuplicate = 2800;
	        bytesIn = 11000;
	        bytesOut = 2200;
	        bytesOutOfOrder = 2600;
	        bytesRetransmitted = 0;
	        cellularFallback = 0;
	        cellularRRCConnected = 0;
	        connected = 1;
	        connectedInterfaceType = "INTERFACE_TYPE_WIFI";
	        "connectionEstablishmentTime_msecs" = 8;
	        connectionReuseCount = 0;
	        "currentRTT_msecs" = 12;
	        "flowDuration_msecs" = 34538;
	        interfaceType = "INTERFACE_TYPE_WIFI";
	        kernelReportedStalls = 0;
	        kernelReportingConnectionStalled = 0;
	        kernelReportingReadStalled = 0;
	        kernelReportingWriteStalled = 0;
	        packetsDuplicate = 0;
	        packetsIn = 12;
	        packetsOut = 7;
	        packetsOutOfOrder = 0;
	        packetsRetransmitted = 0;
	        "smoothedRTT_msecs" = 11;
	        synRetransmissionCount = 0;
	        tcpFastOpen = 0;
	        "timeToConnectionEstablishment_msecs" = 28;
	        "timeToConnectionStart_msecs" = 20;
	        "timeToDNSResolved_msecs" = 19;
	        "timeToDNSStart_msecs" = 3;
	        trafficClass = 0;
	    };
	    delegated = 0;
	    reportReason = "REPORT_REASON_DATA_STALL_AT_APP_LAYER";
	}
Nov  9 10:04:50 haoge-iPhone com.apple.CDScheduler[26] <Error>: SysAdmChk: Throttling activity execution. memFlags:0x1 thermalLevel:0x0
Nov  9 10:04:50 haoge-iPhone com.apple.CDScheduler[26] <Error>: SysAdmChk: Throttling activity execution. memFlags:0x1 thermalLevel:0x0
Nov  9 10:04:50 haoge-iPhone backupd[2234] <Notice>: (Error) NPSLogging: <NPSDomainAccessor.m +[NPSDomainAccessor resolveActivePairedDevicePairingID:pairingDataStore:]:40> Failed to resolve pairing ID ((null)) or data store ((null)) for active device
Nov  9 10:04:51 haoge-iPhone backupd[2234] <Notice>: (Error) NPSLogging: <NPSDomainAccessor.m +[NPSDomainAccessor resolveActivePairedDevicePairingID:pairingDataStore:]:40> Failed to resolve pairing ID ((null)) or data store ((null)) for active device
Nov  9 10:04:51 haoge-iPhone backupd[2234] <Warning>: INFO: Cloud photos is enabled and fully synced. Excluding camera roll from backup.
Nov  9 10:04:51 haoge-iPhone backupd[2234] <Warning>: INFO: Replaying journal for device: D:33cd565750e53ef696cce38f539e04496b57ea09
Nov  9 10:04:52 haoge-iPhone backupd[2234] <Warning>: INFO: Journal actions: (null)
Nov  9 10:05:05 haoge-iPhone backupd[2234] <Warning>: INFO: CK Cache: Analyzed existing cache in 13.335 s
Nov  9 10:05:05 haoge-iPhone backupd[2234] <Warning>: INFO: Scanning files for changes
Nov  9 10:05:11 haoge-iPhone backupd[2234] <Error>: MKBBackupValidateKey: Key blob is for a file with a different inode (58595021 instead of 3994981)
Nov  9 10:05:12 haoge-iPhone backupd[2234] <Error>: MKBBackupValidateKey: Key blob is for a file with a different inode (58595013 instead of 1485)
Nov  9 10:05:12 haoge-iPhone backupd[2234] <Error>: MKBBackupValidateKey: Key blob is for a file with a different inode (58579068 instead of 1040)
Nov  9 10:05:17 haoge-iPhone mediaserverd[28] <Notice>: '' (pid = 1337) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_None
Nov  9 10:05:17 haoge-iPhone aggregated[2264] <Warning>: Looks like aggd crashed. Not counting as reboot.
Nov  9 10:05:17 haoge-iPhone aggregated[2264] <Warning>: Didn't log uptime data as aggd might have crashed or this is a first boot.
Nov  9 10:05:17 haoge-iPhone aggregated[2264] <Warning>: BTA job already scheduled for ADDaily

**Comment by AloneMonkey** [comment]
那你看下编译过程中这个CYPlatform_SFRZ.framework签名了吗？

**Comment by zhoupenghao** [comment]
现在新建的工程没有link这个库，怎么会出现这个库呢

**Comment by AloneMonkey** [comment]
不是你自己link的？那你看是不是app自带的

**Comment by zhoupenghao** [comment]
也不是，好像是加在了 monkeyDev的库路径下面的

**Comment by zhoupenghao** [comment]
是不是会自动去编译它了

**Comment by zhoupenghao** [comment]
我看了一下，确实是添加在了Monkeydev的  framework路径下面包含了，libsubstrate  dylib的一个路径下，是不是编译进去了  ，但是没有重签，是这个意思吗

**Comment by AloneMonkey** [comment]
看xcode编译流程里面有没有重签，有日志的。
