### ISSUE TITLE
Build input files cannot be found: '/usr/lib/libc++.dylib', '/usr/lib/libstdc++.dylib'. 

### ISSUE THREAD

**Issue by tianxiawoyougood** [AloneMonkey/MonkeyDev#354]
Build input files cannot be found: '/usr/lib/libc++.dylib', '/usr/lib/libstdc++.dylib'. Did you forget to declare these files as outputs of any script phases or custom build rules which produce them?

**Comment by tianxiawoyougood** [comment]
Xcode 15.0.1

**Comment by qiniuGe** [comment]
这里已经解决了#349，target选dylib那个
![截屏2024-02-21 16 39 25](https://github.com/AloneMonkey/MonkeyDev/assets/138416368/30d90d71-6472-4787-8519-32c1a675ed5f)

**Comment by tianxiawoyougood** [comment]
done

**Comment by wangwanjie** [comment]
> 这里已经解决了#349，target选dylib那个 ![截屏2024-02-21 16 39 25](https://private-user-images.githubusercontent.com/138416368/306554277-30d90d71-6472-4787-8519-32c1a675ed5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDM5NjMsIm5iZiI6MTcwODk0MzY2MywicGF0aCI6Ii8xMzg0MTYzNjgvMzA2NTU0Mjc3LTMwZDkwZDcxLTY0NzItNDc4Ny04NTE5LTMyYzFhNjc1ZWQ1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxMDM0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDk3NjEwNzJhYzIwN2ExNWRjZjdkOWE1NTMwNjYxMmE5Y2NlOTQ2YTU1MGI5NTYzZjZjNDIxODIwYjNlMzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZKWfspapFyfkwF6xKlR0Yflr3oTzBYmIMntrq3s9Lys)

tks
