### ISSUE TITLE
Message from debugger: Terminated due to signal 9

### ISSUE THREAD

**Issue by liwenDeng** [AloneMonkey/MonkeyDev#36]
在调试斗鱼进入直播间页面时程序会直接终止，log 提示: Message from debugger: Terminated due to signal 9。 想知道有办法处理吗？

**Comment by AloneMonkey** [comment]
反调试吧，找到反调试代码，处理掉、

**Comment by AloneMonkey** [comment]
你更新下MonkeyDev再试试，记得开启AntiAntiDebug里面的sysctl的hook。
