### ISSUE TITLE
请教个问题,放入砸壳了的ipa后一直报can't find decrypted arch!!!

### ISSUE THREAD

**Issue by jveryl** [AloneMonkey/MonkeyDev#39]
packing...
Print: Entry, "CFBundleDisplayName", Does Not Exist
Print: Entry, "CFBundleURLTypes", Does Not Exist
has arm7 arch? true
has arm64 arch? false
is fat file? true
decrypted arch num? 0
can't find decrypted arch!!!
Command /bin/sh failed with exit code 1

请问下是什么原因呢

**Comment by AloneMonkey** [comment]
can't find decrypted arch!!!  没有砸壳，之前的issues找找

**Comment by jveryl** [comment]
谢谢了啊,可不可以再问一个问题,
10.13.1系统下用cycript会报这个错,请问怎么解决呢
LeedeMacBook-Pro:~ Jveryl$ /Users/Jveryl/Desktop/Crash/cycript_0/cycript -r 192.168.0.1
dyld: Library not loaded: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/libruby.2.0.0.dylib
  Referenced from: /Users/Jveryl/Desktop/Crash/cycript_0/Cycript.lib/cycript-apl
  Reason: image not found
Abort trap: 6

**Comment by AloneMonkey** [comment]
你看下这个目录/System/Library/Frameworks/Ruby.framework/Versions/下面是3.0的版本，自己创建一个2.0的符号链接到新的dylib

**Comment by jveryl** [comment]
非常感谢
