### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by haipengchen** [AloneMonkey/MonkeyDev#4]
安装官方步骤下来后，新建一个MonkeyApp,点击运行后，报TargetApp does not have an architecture that iPhone 6s can execute.
![1122233](https://user-images.githubusercontent.com/16647664/28698915-f6961060-7378-11e7-8032-fe6e236e66b7.png)

**Comment by AloneMonkey** [comment]
你砸壳应用是怎么获取的，里面没有arm64的架构。

**Comment by haipengchen** [comment]
上面截图的是没有放入任何应用，直接空白运行出现的。
下面是我通过pp助手下载的越狱微信应用
![22333](https://user-images.githubusercontent.com/16647664/28699188-b600b53a-737a-11e7-9e41-4afa854a31a1.png)

**Comment by ZuhanLin** [comment]
![image](https://user-images.githubusercontent.com/5183529/28702982-647a264c-7393-11e7-87b7-4bd57b5db08b.png)
安装成功，启动失败，请问是什么原因呢？

**Comment by AloneMonkey** [comment]
@ZuhanLin https://github.com/AloneMonkey/MonkeyDev/wiki/Q&A#nine

**Comment by AloneMonkey** [comment]
@haipengchen 你跑的模拟器？

**Comment by haipengchen** [comment]
嗯

**Comment by AloneMonkey** [comment]
@haipengchen 模拟器跑不了，选真机

**Comment by ZuhanLin** [comment]
有好的越狱商店推荐一下吗？微信越狱的没有找到啊

**Comment by justinsongtx** [comment]
> 你砸壳应用是怎么获取的，里面没有arm64的架构。

我也遇到这个问题，5s真机运行，pp助手获取的微信ipa，自己砸壳了一遍也是这个问题，求解
