### ISSUE TITLE
特殊权限的授权问题

### ISSUE THREAD

**Issue by zyc199847** [AloneMonkey/MonkeyDev#40]
前几天试着调试qq时，发现在确保没有其它hook的情况下，qq请求siri权限时会引发crash，在设置菜单中关闭siri权限后可以登陆。同时qq的推送等其它服务失效，但没有造成闪退。

是否有方法使targetAPP的特殊权限正常工作？还是说因为相同的bundle id不能签发entitlement而彻底无解？

**Comment by AloneMonkey** [comment]
推送是有专门的推送证书的，重签后就没法推送。  siri的权限的话我还没试过，不确定在entitlement加上是不是就ok

**Comment by zyc199847** [comment]
所以目前重签后特殊权限就确实无解了？

**Comment by AloneMonkey** [comment]
所以你可以试试改entitlement，我记得qq不会crash把

**Comment by zyc199847** [comment]
Thanks 我试试
