### ISSUE TITLE
非越狱App集成后，CFBundleIdentifier 被修改

### ISSUE THREAD

**Issue by shishirui** [AloneMonkey/MonkeyDev#42]
用的是这个方法：[非越狱App集成](https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%9D%9E%E8%B6%8A%E7%8B%B1App%E9%9B%86%E6%88%90)

按照这个方法注入了dylib并使用`createIPA.command`生成了ipa文件，发现新的ipa中info.plist被修改了，对比之后发现是`CFBundleIdentifier`变了，请问有没有办法让 `CFBundleIdentifier` 不变？

我看一下，是 /opt/MonkeyDev/Tools/pack.sh:209 修改了CFBundleIdentifier：

    /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier $PRODUCT_BUNDLE_IDENTIFIER" "$BUILD_APP_PATH/Info.plist"

请问为什么要修改 CFBundleIdentifier 呢？

**Comment by AloneMonkey** [comment]
你都看到了代码就知道怎么不修改了

**Comment by shishirui** [comment]
那您的代码中修改CFBundleIdentifier的本身用意是为什么呢？只是纯好奇。

**Comment by AloneMonkey** [comment]
装多个相同的app

**Comment by shishirui** [comment]
哦明白了～
