### ISSUE TITLE
有签名了，但是还是提示签名无效

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#43]
Showing Recent Messages
/Users/iMac/Library/Developer/Xcode/DerivedData/ZYAppFactory-bfnxgfsussiwkjdddrdcsvnamcaj/Build/Products/Release-iphoneos/ZYAppFactory.app/Frameworks/SFBLE.framework: replacing existing signature;

Dec  5 20:52:34 haoge-iPhone installd[820] <Error>: 0x16e12f000 +[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]: 142: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.tCWJRX/extracted/Payload/ZYAppFactory.app/Frameworks/SFBLE.framework : 0xe8008019 (The application does not have a valid signature.)
Dec  5 20:52:34 haoge-iPhone installd[820] <Error>: 0x16e12f000 -[MIInstaller performInstallationWithError:]: Verification stage failed
Dec  5 20:52:35 haoge-iPhone mobile_installation_proxy[815] <Error>: 0x16e247000 __MobileInstallationInstallForLaunchServices_block_invoke222: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.tCWJRX/extracted/Payload/ZYAppFactory.app/Frameworks/SFBLE.framework : 0xe8008019 (The application does not have a valid signature.)" UserInfo={LibMISErrorNumber=-402620391, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=142, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.tCWJRX/extracted/Payload/ZYAppFactory.app/Frameworks/SFBLE.framework : 0xe8008019 (The application does not have a valid signature.)}
Dec  5 20:52:35 haoge-iPhone mobile_installation_proxy[815] <Error>: 0x16e12f000 handle_install: Installation failed: Error Domain=LaunchServicesError Code=0 "(null)" UserInfo={Error=ApplicationVerificationFailed, ErrorDetail=-402620391, ErrorDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.tCWJRX/extracted/Payload/ZYAppFactory.app/Frameworks/SFBLE.framework : 0xe8008019 (The application does not have a valid signature.)}

**Comment by AloneMonkey** [comment]
静态库就认认真真的当静态库用，不要非得给他带个动态库的帽子。
