### ISSUE TITLE
LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted

### ISSUE THREAD

**Issue by dannyZhou** [AloneMonkey/MonkeyDev#44]
Reproduce:
1. Install MonkeyDev 
2. create project of monkeyDev 
3. download ipa from https://www.25pp.com/ios/detail_1333696/ 
4. move ipa to TargetApp
5. build project and run 

Error: 

> 2017-12-06 10:02:17.359524 putong[1004:16620] [AntiAntiDebug Init]
2017-12-06 10:02:17.696708 putong[1004:16620] 
               🎉!!！congratulations!!！🎉
👍----------------insert dylib success----------------👍
2017-12-06 10:02:17.712327 putong[1004:16620] Method Trace is disable
LLVM Profile Error: Failed to write file "default.profraw": Permission denied

**Comment by AloneMonkey** [comment]
1. Updated MonkeyDev to the latest
2. Create a new MonkeyApp project 
3. open `AntiAntiDebug.m` , remove the comment of following line of code

```
rebind_symbols((struct rebinding[1]){{"sysctl", my_sysctl, (void*)&orig_sysctl}},1);
```
4. download ipa from https://www.25pp.com/ios/detail_1333696/
5. move ipa to TargetApp
6. build project and run

**Comment by dannyZhou** [comment]
Resolved. Thank you very much!

**Comment by LuckyChen73p** [comment]
庆哥这个方法我试了抖音和TikTok都不生效, 请问还有其他办法吗?

**Comment by LemaMichael** [comment]
> 庆哥这个方法我试了抖音和TikTok都不生效, 请问还有其他办法吗?

I'm having the same issue. Were you able to solve?
