### ISSUE TITLE
不能用个人开发者账号签名吗

### ISSUE THREAD

**Issue by Moredistant** [AloneMonkey/MonkeyDev#45]
Code Signing Error: Signing for "testmonkeyDylib" requires a development team. Select a development team in the project editor.

**Comment by AloneMonkey** [comment]
可以啊，动态库也要选择证书的啊。

**Comment by Moredistant** [comment]
感谢~已解决！

**Comment by lyb5834** [comment]
> 可以啊，动态库也要选择证书的啊。

请问动态库怎么选择证书？xcode 11
