### ISSUE TITLE
logos  语法在monkeydev中   应该怎么处理呢

### ISSUE THREAD

**Issue by zhoupenghao** [AloneMonkey/MonkeyDev#46]
logos  语法在monkeydev中   应该怎么处理呢，因为hooks  下的一些.mm是   logos语法的，在xcode 好像无法识别编译

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%9D%9E%E8%B6%8A%E7%8B%B1App%E9%9B%86%E6%88%90#%E5%8A%A8%E6%80%81%E5%BA%93%E8%B0%83%E8%AF%95
