### ISSUE TITLE
archive打包报错

### ISSUE THREAD

**Issue by jveryl** [AloneMonkey/MonkeyDev#47]
For Xcode Build Phase use only
Command /bin/sh failed with exit code 1
如上提示..

请问下该如何解决呀

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%9D%9E%E8%B6%8A%E7%8B%B1App%E9%9B%86%E6%88%90#%E7%94%9F%E6%88%90ipa
