### ISSUE TITLE
无法编译target specifies product type 'com.apple.product-type.tool'

### ISSUE THREAD

**Issue by Does4U** [AloneMonkey/MonkeyDev#48]
系统版本：10.13.1
Xcode版本: 9.2 (9C40b)

创建 Command-line Tools项目，真机调试，编译错误提示：

target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform

**Comment by AloneMonkey** [comment]
xcode-select -s 切换，然后重新执行 md-install

**Comment by oschanger** [comment]
Xcode12上要改下安装脚本，把这行macosxSDKSpecificationsPath改下:
macosxSDKSpecificationsPath=$macosSdkPlatformPath/Developer/Library/Xcode/PrivatePlugIns/IDEOSXSupportCore.ideplugin/Contents/Resources
