### ISSUE TITLE
非越狱机器 tweak编译失败

### ISSUE THREAD

**Issue by GDAwen** [AloneMonkey/MonkeyDev#49]
log如下：

Preparing to run Xcode Build Phase...
use default localhost
Signing /Users/Andrew/Library/Developer/Xcode/DerivedData/MonkeyTweak-hgehcklwlfxkkmfbqnuldhetixut/Build/Products/Debug-iphoneos/MonkeyTweak.dylib with codesign... Done.
Failed to locate sshpass. Is sshpass installed? If not, brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
Command /bin/sh failed with exit code 1

非越狱机器，iOS11.2系统，cmd+b  报错，请问是什么原因了？

**Comment by AloneMonkey** [comment]
非越狱机器就老老实实玩MonkeyApp，基础理论学好先，别老想着搞点大事情。

**Comment by GDAwen** [comment]
额，逆向这块儿我刚开始学习，其实没有想着要搞点大事情，我是想将《iOS应用逆向工程》第二版前四章上的实验案例一个个实践一遍，加深理解。

**Comment by GDAwen** [comment]
嗯嗯， 谢谢您的解答，这个部分的wiki我有看过，实验demo还在熟悉中。我目前还在看《iOS应用逆向工程》书的第二部分，还没有学到app的砸壳、反编译，我慢慢来，不急。谢谢您的解答

**Comment by AloneMonkey** [comment]
不用一开始就上手搞应用，先把整个流程搞明白，后面再来搞就轻松很多了

**Comment by GDAwen** [comment]
哈哈哈 谢谢您的建议，我目前最好还是按照书上一步步来，像您说的那样，先把整个流程搞明白
