### ISSUE TITLE
调试支付宝闪退

### ISSUE THREAD

**Issue by wanchangjun** [AloneMonkey/MonkeyDev#5]
设备:iOS 8.2越狱机
步骤:
1.砸壳支付宝等到aliwallet.ipa
2.解压并修改mach-o的__restrict为__pppppppp
3.用A套证书重新签名得到alliwallet_reg.ipa
4.用A套证书运行
运行闪退xcode控制台输出内容:
![2017-07-28 10 04 06](https://user-images.githubusercontent.com/7578275/28699454-4a8b469c-737c-11e7-8fbd-779809d37b1e.png)
设备控制台输出内容:
![2017-07-28 10 09 25](https://user-images.githubusercontent.com/7578275/28699559-15d6f012-737d-11e7-9674-6924f84f4df9.png)

**Comment by wanchangjun** [comment]
另外:MonkeyAliWalletDylib编译是用ldid签名的

**Comment by AloneMonkey** [comment]
已经跑起来了的话，应该是应用本身的检测

**Comment by wanchangjun** [comment]
@AloneMonkey 恩，想请教下这方面有啥思路没有

**Comment by AloneMonkey** [comment]
我没有试过。

**Comment by GPX-NSlog** [comment]
@wanchangjun 问题解决了么

**Comment by wanchangjun** [comment]
@GPX-NSlog 解决了，好像是支付宝代码里面对bundleId做了限制，咱们重签名的时候bundleId变了，想办法把签名bundleId改成和支付宝一模一样就行，我把作者写的重签名脚本稍微改了下

**Comment by wanchangjun** [comment]
@GPX-NSlog 解决了，好像是支付宝代码里面对bundleId做了限制，咱们重签名的时候bundleId变了，想办法把签名bundleId改成和支付宝一模一样就行

**Comment by loongkobe** [comment]
@wanchangjun 能写详细点怎么改吗，我也是调试直接闪退了
