### ISSUE TITLE
创建的是APP类型,但是把header的.h文件引用进来会报错

### ISSUE THREAD

**Issue by jveryl** [AloneMonkey/MonkeyDev#52]
请问下,我引用的class-dump出来的header的.h文件,应该放哪里?

我如果不调用.h文件里的方法,是不会报错的.
但是调用就报ld: symbol(s) not found for architecture arm64
没找到64位支持

**Comment by AloneMonkey** [comment]
https://github.com/AloneMonkey/WeChatPod

看看怎么调的
