### ISSUE TITLE
无法使用Reveal调试

### ISSUE THREAD

**Issue by GPX-NSlog** [AloneMonkey/MonkeyDev#53]
![image](https://user-images.githubusercontent.com/17864687/34556369-f5c105fc-f170-11e7-9517-c4815dfcc7f9.png)
出现这样的情况,是我的操作不对?    
未安装MonkeyApp到Xcode 是能够使用Reveal进行真机调试的.  百度了下 好像是Reveal版本低的原因

**Comment by GPX-NSlog** [comment]
已经解决,替换了MonkeyApp  自带的RevealServer.framework

**Comment by no9xavier** [comment]
文件位置：/opt/MonkeyDev/Frameworks
