### ISSUE TITLE
logos tweak资源文件

### ISSUE THREAD

**Issue by sephilex** [AloneMonkey/MonkeyDev#54]
请问进行logos tweak开发时，图片等一些资源文件应该怎样添加

**Comment by AloneMonkey** [comment]
放在layout里面，然后使用的时候使用手机的绝对路径。

**Comment by sephilex** [comment]
我有看见你之前在iosre的回答，但monkeydev的logos tweak工程没有这个文件夹吧，我在package同级目录下创建layout不行，将layout添加到tweak的taraget也不行




| |
|
|
邮箱：sephilex@163.com
|

签名由 网易邮箱大师 定制

在2018年01月06日 11:08，Alone_Monkey 写道：

放在layout里面，然后使用的时候使用手机的绝对路径。

**Comment by AloneMonkey** [comment]
Package  目录就相当于layout  ，  直接放这个下面就可以

**Comment by sephilex** [comment]
Package相当于手机文件系统的根目录，谢谢

**Comment by zhuguoliang1014** [comment]
> Package 目录就相当于layout ， 直接放这个下面就可以

![Snip20200131_2](https://user-images.githubusercontent.com/17693927/73537928-a4c4ca00-4464-11ea-8649-b7c0c94b5212.png)
