### ISSUE TITLE
微信环境验证问题

### ISSUE THREAD

**Issue by dakezuo** [AloneMonkey/MonkeyDev#57]
这个工具会对微信进行重签名吗，微信不是会有对bundleID等的验证吗，这部分应该怎么来解决呢

**Comment by AloneMonkey** [comment]
使用aaa，会用默认的bundle id，其它重签检测问题本工具不解决！

**Comment by gongjujun** [comment]
@AloneMonkey  使用aaa签名,这里应该怎么选
![image](https://user-images.githubusercontent.com/12054470/34975886-e111fc26-face-11e7-8204-bf2749c862df.png)

**Comment by AloneMonkey** [comment]
@gongjujun 选证书，这是一道正向开发题啊，朋友！
