### ISSUE TITLE
sudo ./md-install 报错

### ISSUE THREAD

**Issue by ddoger** [AloneMonkey/MonkeyDev#58]
Downloading MonkeyDev base from Github...
dyld: mach-o, but built for simulator (not macOS)
./md-install: line 112: 36328 Abort trap: 6           "$curlPath" --output "$targetPath" "$sourceUrl"
Failed to download https://codeload.github.com/AloneMonkey/MonkeyDev/tar.gz/master to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/md-install.Sa36Pi3Y/file.tar.gz

**Comment by AloneMonkey** [comment]
直接运行这个试试

sudo /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/AloneMonkey/MonkeyDev/master/bin/md-install)"

下载失败一般都是网络不好。

**Comment by ddoger** [comment]
报错:dyld: mach-o, but built for simulator (not macOS)

**Comment by AloneMonkey** [comment]
重装curl

**Comment by ddoger** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char const *argv[])
{
	if (argc>1)
	{
		char str[]="/usr/local/opt/curl/bin/curl";
		for (int i = 0; i < argc; ++i)
		{
			if (i>0)
			{
				strcat(str," ");
				strcat(str,argv[i]);
			}
		}
		printf("count %s\n",str);
		system(str);
	}
	return 0;
}

**Comment by ddoger** [comment]
gcc -o curl curl.mm生成了curl的执行文件替换了系统的curl 还是报错
错误信息：

**Comment by ddoger** [comment]
gcc -o curl curl.mm生成了curl的执行文件替换了系统的curl 还是报错

错误信息：
Downloading MonkeyDev base from Github...
./md-install: line 112: 52603 Segmentation fault: 11  "$curlPath" --output "$targetPath" "$sourceUrl"
Failed to download https://codeload.github.com/AloneMonkey/MonkeyDev/tar.gz/master to /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/md-install.3LnpRPgK/file.tar.gz

curl.mm的内容：
int main(int argc, char const *argv[])
{
	if (argc>1)
	{
		char str[]="/usr/local/opt/curl/bin/curl";
		for (int i = 0; i < argc; ++i)
		{
			if (i>0)
			{
				strcat(str," ");
				strcat(str,argv[i]);
			}
		}
		printf("count %s\n",str);
		system(str);
	}
	return 0;
}

跪了...

**Comment by AloneMonkey** [comment]
`"$curlPath" --output "$targetPath" "$sourceUrl"`

打印这个命令，然后自己执行找找问题

**Comment by ddoger** [comment]
脚本第120行赋值虽然没报错但在我电脑上没生效 
                curlPath=`which curl` || \
		panic $? "Failed to get curl path"
       直接把"$curlPath"替换成本地的curl安装路径 安装成功.....

**Comment by carppond** [comment]
'/usr/local/Cellar/curl/7.66.0/bin/curl' --output "$targetPath" "$sourceUrl" || \
		panic $? "Failed to download $sourceUrl to $targetPath"
按照上面步骤，修改了curl路径，一直报错
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out
Failed to download https://raw.githubusercontent.com/AloneMonkey/frida-ios-dump/3.x/dump.py to /opt/MonkeyDev/bin/dump.py

**Comment by carppond** [comment]
https://www.v2ex.com/t/353655
我通过文章最后一条解决、
