### ISSUE TITLE
启动微信时闪退

### ISSUE THREAD

**Issue by haipengchen** [AloneMonkey/MonkeyDev#6]
dyld: Library not loaded: @executable_path/Frameworks/libwechat_01Dylib.dylib
  Referenced from: /var/containers/Bundle/Application/7DF43DA9-EAE5-4FCC-B0E0-EFC7CF4C040B/wechat_01.app/WeChat
  Reason: no suitable image found.  Did find:
	/var/containers/Bundle/Application/7DF43DA9-EAE5-4FCC-B0E0-EFC7CF4C040B/wechat_01.app/Frameworks/libwechat_01Dylib.dylib: code signature invalid for '/var/containers/Bundle/Application/7DF43DA9-EAE5-4FCC-B0E0-EFC7CF4C040B/wechat_01.app/Frameworks/libwechat_01Dylib.dylib'

	/private/var/containers/Bundle/Application/7DF43DA9-EAE5-4FCC-B0E0-EFC7CF4C040B/wechat_01.app/Frameworks/libwechat_01Dylib.dylib: code signature invalid for '/private/var/containers/Bundle/Application/7DF43DA9-EAE5-4FCC-B0E0-EFC7CF4C040B/wechat_01.app/Frameworks/libwechat_01Dylib.dylib'

**Comment by AloneMonkey** [comment]
在bin目录下运行  sudo ./md-update 更新一下，再试试
