### ISSUE TITLE
disable cycript and reveal on release build.

### ISSUE THREAD

**Issue by simpzan** [AloneMonkey/MonkeyDev#60]
I use some modified apps for daily use, so I install the app with release build.
but the 2 servers are enabled on release build too, it is a little risky.

**Comment by simpzan** [comment]
disable cycript for release build, enclose `CYListenServer` with `#ifdef DEBUG`
disable reveal for release build, remove `RevealServer.framework` in linked framework list, add `-framework RevealServer` in linker flags settings for debug build.

**Comment by AloneMonkey** [comment]
ok，thanks！ I will fix at night.

**Comment by AloneMonkey** [comment]
@simpzan  updated！

**Comment by iOSleep** [comment]
great

**Comment by simpzan** [comment]
@AloneMonkey wonderful! amazed by your response.
