### ISSUE TITLE
请问如何调试dylib

### ISSUE THREAD

**Issue by xinyangslove** [AloneMonkey/MonkeyDev#61]
我使用xocde集成monkeydev，然后新建了一个tweak工程，使用钩子的时候进入了安全模式，我想断点调试查看是哪里的问题，但是xcode打断点后，common+b 安装后xcode并没有断点效果。

请问如何给dylib打断点？

**Comment by AloneMonkey** [comment]
用MonkeyApp工程调试，具体看https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%9D%9E%E8%B6%8A%E7%8B%B1App%E9%9B%86%E6%88%90#%E5%8A%A8%E6%80%81%E5%BA%93%E8%B0%83%E8%AF%95

**Comment by xinyangslove** [comment]
嗯，看到了，初步的原因可能是我指定了设备的ip导致安装是openssh无线方式安装运行的，那么怎么通过usb运行的方式去动态调试运行呢？
![image](https://user-images.githubusercontent.com/7271148/36531259-4a33fe8e-17f8-11e8-8064-03708db305be.png)
如果删掉以下的设备ip和密码又报错
![image](https://user-images.githubusercontent.com/7271148/36531415-b6a64fc2-17f8-11e8-8dce-b3e1598ff130.png)

**Comment by xinyangslove** [comment]
接着我尝试在共享里面打开“远程登陆”，然后再次编译变成另一个错误了
![image](https://user-images.githubusercontent.com/7271148/36540280-bb0e52b4-1814-11e8-954a-0eb4db264d19.png)

我尝试手动在命令行输入 ssh -p22 root@localhost 提示要输入密码，这个密码既不是手机的ssh密码，也不是ssh localhost密码很奇怪

**Comment by AloneMonkey** [comment]
我说的是创建monkeyapp工程，不是创建tweak工程
