### ISSUE TITLE
iPhone has denied the launch request.

### ISSUE THREAD

**Issue by maibou8888** [AloneMonkey/MonkeyDev#63]
运行到手机上打不开  xcode报这个错误 iPhone has denied the launch request.

**Comment by xdestiny110** [comment]
@maibou8888 最后是怎么解决的呢？

**Comment by KevinGong2013** [comment]
重启手机  Sticktron/g0blin#109

**Comment by MrQQQQQQQQQQ** [comment]
我刚刚也遇到，是因为target app 没有脱壳
