### ISSUE TITLE
IOSurface/IOSurfaceRef.h  file not found

### ISSUE THREAD

**Issue by CokePokes** [AloneMonkey/MonkeyDev#64]
Error is here in apple's header when #import <UIKit/UIKit.h> in dylib & targeting iOS device

/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/System/Library/Frameworks/CoreImage.framework/Headers/CIImage.h:16:9: 'IOSurface/IOSurfaceRef.h' file not found

#if !TARGET_OS_IPHONE
#import <IOSurface/IOSurface.h>
#elif !TARGET_OS_SIMULATOR
#import <IOSurface/IOSurfaceRef.h>
#endif

**Comment by AloneMonkey** [comment]
Can you provide the project source code?

**Comment by AloneMonkey** [comment]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/IOSurface.framework

Does this file exist?

**Comment by CokePokes** [comment]
No it does not.

**Comment by AloneMonkey** [comment]
May be removed in iPhoneOS 11.2 sdk version,  It exists on my computer(iPhoneOS11.0 sdk version)

**Comment by Co2333** [comment]
Can you speak Chinese !!!!! 丑猴子

**Comment by AloneMonkey** [comment]
Another computer has this file in  iPhoneOS 11.2 sdk version, It may be your sdk problem?

**Comment by Lakr233** [comment]
[IOSurface.framework.zip](https://github.com/AloneMonkey/MonkeyDev/files/1770184/IOSurface.framework.zip)

**Comment by CokePokes** [comment]
Actually `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/IOSurface.framework` does exist. I was looking in the wrong directory. This issue only happens with the monkeydev created projects.

**Comment by CokePokes** [comment]
So it turns out the issue is unrelated. My PrivateFrameworks were somehow to blame.

**Comment by mwpcheung** [comment]
monkeydev's include path maybe like this:
![image](https://user-images.githubusercontent.com/5516920/39247014-cd04e11c-485d-11e8-99a9-0c420b386008.png)
extract the zip file  https://github.com/AloneMonkey/MonkeyDev/files/1770184/IOSurface.framework.zip  to /opt/theos/vendor/lib

**Comment by seeskyline** [comment]
> So it turns out the issue is unrelated. My PrivateFrameworks were somehow to blame.

I encountered the same problem. Could you detail the your solution for me? What's wrong with PrivateFrameworks. Thank you :)
