### ISSUE TITLE
您好，想请教一下关于dyld: Library not loaded: 的问题

### ISSUE THREAD

**Issue by github410117** [AloneMonkey/MonkeyDev#65]
`dyld: Library not loaded: /Library/MobileSubstrate/DynamicLibraries/ddy.dylib
  Referenced from: /var/containers/Bundle/Application/C0EEBFB4-22AC-49A7-A3AF-61323CD27214/xhtest.app/Frameworks/libxhtestDylib.dylib
  Reason: image not found`
添加自己编写的dylib报错，我看了您的Wiki two，添加依赖(默认是有添加的),然后我仔细看了文档，我也把这个dylib放到了/opt/MonkeyDev/Framework目录下，然后再拉入build phases的Link Binary With Libraries，运行也是报这个错，我直接用deb安装是可以成功的，卡了一下午实在是不知道问题出在哪，可能是很小白的错误，希望能得到您的指点，万分感谢！元宵快乐！

**Comment by AloneMonkey** [comment]
你加的是现成的dylib文件？如果是的话，看frida那个(wiki里有)怎么加，一样的步骤。

**Comment by AloneMonkey** [comment]
你加的是现成的dylib文件？如果是的话，看frida那个(wiki里有)怎么加，一样的步骤。
