### ISSUE TITLE
[AntiAntiDebug Init] LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted

### ISSUE THREAD

**Issue by alpface** [AloneMonkey/MonkeyDev#68]
xcode 运行app 进入启动页面后闪退:
控制台显示:
`[AntiAntiDebug Init]
LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted`

但是直接在iPhone可以正常运行此app，估计还受反调试影响。

- Mac OS 10.12.6
- Xcode9.2
- iOS 11.2.6

**Comment by AloneMonkey** [comment]
反调试的问题自己解决。

**Comment by alpface** [comment]
#####已经找到解决方法:
在AntiAntiDebug.m中去掉下面这行代码的注释，xcode 运行即可，
希望其他朋友遇到此类问题能看到解决方案:
```
rebind_symbols((struct rebinding[1]){{"sysctl", my_sysctl, (void*)&orig_sysctl}},1);
```

**Comment by x122536638** [comment]
我也遇到这个情况了,我导入项目的app是自己从手机上砸壳的app包,取消注释上面的代码还是一样蹦,sad
