### ISSUE TITLE
有没有砸壳的教程

### ISSUE THREAD

**Issue by JxbSir** [AloneMonkey/MonkeyDev#7]
dumpdecrypted貌似4年没有维护了，砸不成功

**Comment by AloneMonkey** [comment]
@JxbSir dumpdecrypted 和 Clutch 都可以砸。亲测。或者你看下我这个:https://github.com/AloneMonkey/dumpdecrypted

**Comment by JxbSir** [comment]
@AloneMonkey 
是不是砸壳时需要用越狱手机？

**Comment by AloneMonkey** [comment]
@JxbSir 是的，不然你就从XX助手下载越狱应用。
