### ISSUE TITLE
无法砸壳

### ISSUE THREAD

**Issue by usualwyy** [AloneMonkey/MonkeyDev#72]
其他砸壳方法不用说了，我有砸过壳的可执行文件，但是用款框架砸壳方便点。
现在自动砸壳砸不开
环境:已越狱 ios 9.3.1
sshpass已配置，本地用ssh连能连上，帐号密码也写在.bashProfile和dump.py里了
请教哪里出了问题

packing...
Print: Entry, "CFBundleDisplayName", Does Not Exist
Print: Entry, "CFBundleURLTypes", Does Not Exist
pulling decrypted ipa from jailbreak device.......
Traceback (most recent call last):
  File "/opt/MonkeyDev/bin/dump.py", line 308, in <module>
    (session, display_name, bundle_identifier) = open_target_app(device, name_or_bundleid)
  File "/opt/MonkeyDev/bin/dump.py", line 251, in open_target_app
    for application in get_applications(device):
TypeError: 'NoneType' object is not iterable
Start the target app 某app
Failed to enumerate applications: unable to connect to remote frida-server: Unable to connect (connection refused)
*** Caught exception: <type 'exceptions.TypeError'>: 'NoneType' object is not iterable
dump.py error
Command /bin/sh failed with exit code 1

**Comment by usualwyy** [comment]
不好意思，解决了，建议用户指引里加上，需要编译并在手机上运行frida-server，这一步不会自动完成

**Comment by AloneMonkey** [comment]
恩，这个步骤是在另外的一个repo : https://github.com/AloneMonkey/frida-ios-dump

**Comment by chenchaozhongvip** [comment]
非越狱编译为什么也报这个错误
