### ISSUE TITLE
Xcode can't edit .xm file

### ISSUE THREAD

**Issue by yikibug** [AloneMonkey/MonkeyDev#78]
![2018-04-04 13 40 58](https://user-images.githubusercontent.com/12478452/38290470-e5796d86-380d-11e8-9bf3-2fe8ee2722b1.png)

**Comment by AloneMonkey** [comment]
Please set file type to `Objective-C++ Source` on navigation right.

**Comment by iOSleep** [comment]
![image](https://user-images.githubusercontent.com/26478957/38295780-c5d1e512-3821-11e8-9882-2be70d395d1b.png)

**Comment by yikibug** [comment]
thanks
