### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by yikibug** [AloneMonkey/MonkeyDev#79]
I created a "Logos Tweak" project, use command + b to install, showing error:
 Showing Recent Issues ssh: connect to host localhost port 22: Connection refused.

**Comment by AloneMonkey** [comment]
Please read wiki 

https://github.com/AloneMonkey/MonkeyDev/wiki/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

thx！

**Comment by AloneMonkey** [comment]
1. run `iproxy 2222 22`
2. set `MonkeyDevDevicePort` to `2222`

**Comment by 393101641** [comment]
> 1. run `iproxy 2222 22`
> 2. set `MonkeyDevDevicePort` to `2222`

额的神呢 一直就困在这一步上 原来如此啊 ！！！！
