### ISSUE TITLE
使用monkeyDev   编译  run  出来  闪退

### ISSUE THREAD

**Issue by wikiInit** [AloneMonkey/MonkeyDev#83]
dyld: Library not loaded: @executable_path/Frameworks/libTangTangDylib.dylib
Referenced from: /var/containers/Bundle/Application/D7D51654-2C34-4AA9-90FB-E065AFD376D0/TangTang.app/tangtang
Reason: no suitable image found. Did find:
/var/containers/Bundle/Application/D7D51654-2C34-4AA9-90FB-E065AFD376D0/TangTang.app/Frameworks/libTangTangDylib.dylib: mach-o, but wrong architecture
/private/var/containers/Bundle/Application/D7D51654-2C34-4AA9-90FB-E065AFD376D0/TangTang.app/Frameworks/libTangTangDylib.dylib: mach-o, but wrong architecture
(lldb)

使用monkeyDev   编译  run  出来  闪退

**Comment by zhangkn** [comment]
dyld: Library not loaded: @executable_path/Frameworks/libweixinDylib.dylib   我也碰到这个问题，你是怎么解决？
