### ISSUE TITLE
pack.sh 报错，不知道是什么原因

### ISSUE THREAD

**Issue by tomatobin** [AloneMonkey/MonkeyDev#84]
`/opt/MonkeyDev/Tools/pack.sh: line 217: 14307 Segmentation fault: 11  "$MONKEYPARSER" codesign -i "$EXPANDED_CODE_SIGN_IDENTITY" -t "$BUILD_APP_PATH"`

这个错误导致Frameworks里的动态库无法正确签名，临时修改了一下，请问是什么原因？

`codesign -v -f -s "${EXPANDED_CODE_SIGN_IDENTITY}" $BUILD_APP_PATH/Frameworks/* 
"$MONKEYPARSER" codesign -i "$EXPANDED_CODE_SIGN_IDENTITY" -t "$BUILD_APP_PATH" `

**Comment by AloneMonkey** [comment]
有没有具体的ipa发我看看，先更新monkeydev确认下问题。

**Comment by tomatobin** [comment]
从pp助手下载的百度地图

**Comment by AloneMonkey** [comment]
测试正常
