### ISSUE TITLE
.m文件中无法使用self

### ISSUE THREAD

**Issue by Guwudao** [AloneMonkey/MonkeyDev#85]
在.m文件中使用self时，会报Receiver type 'XXX' for instance message is a forward declaration的错误

**Comment by AloneMonkey** [comment]
多看看例子怎么写。https://github.com/AloneMonkey/WeChatPod

**Comment by iosluoyang** [comment]
大神，我也是遇到同样的问题，我也在Demo中也做了测试，确实是不能使用self，不知道是为何，能否帮忙传道受业解惑一下，多谢！！
<img width="751" alt="47578e6e-e712-451c-90ce-259df060494e" src="https://user-images.githubusercontent.com/12808629/38683533-533ad366-3e33-11e8-9930-4ba0b3e68975.png">
<img width="727" alt="2018-04-12 10 22 51" src="https://user-images.githubusercontent.com/12808629/38683541-59eeba7e-3e33-11e8-9c1e-5cfe3a63933c.png">

**Comment by Guwudao** [comment]
WeChatPod我在本地运行时报'MDSettingCenter/MDSettingCenter.h' file not found，我的问题就和上面这位朋友的一样，参考WeChatPod好像并不能解决，可以的话还劳烦大神指点一下，谢谢！

**Comment by AloneMonkey** [comment]
@iosluoyang 你声明@interface 继承下NSObject

**Comment by AloneMonkey** [comment]
@Guwudao podfie怎么写的，问题带截图
