### ISSUE TITLE
关于Reveal Framework的问题

### ISSUE THREAD

**Issue by FantasticSkyBaby** [AloneMonkey/MonkeyDev#9]
在手机安装过Reveal插件的情况下/Library/Frameworks/RevealServer.framework/RevealServer存在一个RevealServer.framework，通过Monkey App编译时又会导入一个，此时加载RevealServer.framework库时报错：
Reason:Attempted to load Reveal Library twice. Are you trying to load dynamic library with Reveal Framework already linked?

给出的信息为：Class IBARevealProtocol is implemented in both /private/var/mobile/Containers/Bundle/Application/2F0F5C54-E317-48A2-A737-6DC6061734D5/xin.app/Frameworks/RevealServer.framework/RevealServer and /Library/Frameworks/RevealServer.framework/RevealServer. One of the two will be used. Which one is undefined.

**Comment by AloneMonkey** [comment]
越狱设备需要关掉系统reveal插件的注入，否则会注入两次。
