### ISSUE TITLE
App install失败

### ISSUE THREAD

**Issue by lanvsblue** [AloneMonkey/MonkeyDev#90]
在安装Monkey App时，Xcode报错This application or a bundle it contains has the same bundle identifier as this application or another bundle that it contains. Bundle identifiers must be unique.

<img width="420" alt="1" src="https://user-images.githubusercontent.com/16624177/39284640-ddf4ea5a-4946-11e8-8068-85c1e0bbba1d.png">

**Comment by liaogang** [comment]
我遇到的情况是RevelServer的问题。　设备里装了RevealLoad,再MonkeyDev又拷了个RevealServer.framework来链接。但两个的版本不一样，所以报错了。
