### ISSUE TITLE
运行后闪退

### ISSUE THREAD

**Issue by mumusa** [AloneMonkey/MonkeyDev#95]
[AntiAntiDebug Init]  LLVM Profile Error: Failed to write file "default.profraw":Operation not permitted 

Xcode: 9.1
通过opt/AloneMonkey/bin/md-update 更新的最新版

**Comment by HolmesZhao** [comment]
你怎么关闭了😂发一下解决办法

**Comment by mumusa** [comment]
> 你怎么关闭了😂发一下解决办法
我是18年初下的MonkeyDev报的错，更新到最新的MonkeyDev就好了
