### ISSUE TITLE
能给方法打个中文注释吗？

### ISSUE THREAD

**Issue by Goallying** [AloneMonkey/MonkeyDev#98]
CHOptimizedMethod，CHDeclareMethod1，CHOptimizedClassMethod0，CHOptimizedMethod0，这些都怎么用，填的参数分别什么意思啊。。。

**Comment by Naville** [comment]
培训机构的课程来的吧

**Comment by Goallying** [comment]
@Naville  我以为这些captainHook 宏都是他写的。。。。
